---
title: "code_notebook"
author: "Emily Dombrowski"
date: "2026-05-01"
output: html_document
---

This is a code notebook for my Australian mussel sequence data. I will use it to record the information I do for creating file structures, repositories, etc. My goal is to document errors that I run into, steps I have to take, and justification of parameter deccisions in a central place. I also use this quite a bit to copy my code and error messages...it is definitely a very "beginner level" genomic coding document, so I do include many steps that are glaringly obvious and tend to write in a journal style (for better or worse).

# Table of Contents:   
* [Entry 1: 2026-05-01](#id-section1)
* [Entry 2: 2026-05-04](#id-section2)
* [Entry 3: 2026-05-05](#id-section3)
* [Entry 4: 2026-05-06](#id-section4)
* [Entry 5: 2026-05-07](#id-section5)
* [Entry 6: 2026-05-08](#id-section6)
* [Entry 7: 2026-05-11](#id-section7)
* [Entry 8: 2026-05-12](#id-section8)
* [Entry 9: 2026-05-13](#id-section9)
* [Entry 10: 2026-05-14](#id-section10)
* [Entry 11: 2026-05-17](#id-section11)
* [Entry 12: 2026-05-26](#id-section12)
* [Entry 13: 2026-06-01](#id-section13)
* [Entry 14: 2026-06-02](#id-section14)
* [Entry 15: 2026-06-03](#id-section15)
* [Entry 16: 2026-06-04](#id-section16)
* [Entry 17: 2026-06-05](#id-section17)
* [Entry 18: 2026-06-08](#id-section18)
* [Entry 19: 2026-06-09](#id-section19)
* [Entry 20: 2026-06-11](#id-section20)
* [Entry 21: 2026-06-12](#id-section21)
* [Entry 22: 2026-06-13](#id-section22)
* [Entry 23: 2026-06-15](#id-section23)
* [Entry 24: 2026-06-16](#id-section24)
* [Entry 25: 2026-06-17](#id-section25)

# Scripts
* [trim_array.sh](#id-section13)
* [mapping.sh](#id-section18)
    * There are multiple, annotated versions of this script
* [sam_to_cram.sh](#id-section20)
* [dedup.sh](#id-section24)
* [sam_cram_crai_dedup.sh](#id-section27)

------    
<div id='id-section1'/> 

### Entry 1: 2026-05-01

Coding session: getting on the Lockwood Lab VACC and starting to compile commands for downloading my sequence data

Relevant file paths: 
/netfiles/lockwood_lab/aus_mussels

aus_mussels/
  data/
    raw
    reference

Steps: 
1. Log into VACC on my computer (using ssh)
2. cd into aus_mussels/data/raw
3. Set up tmux: `tmux new -s agrf_transfer`
4. Request wall time to run job over the weekend `srun --pty --mem=8G --time=24:00:00 /bin/bash`
5. Run command from AGRF to download data: `rsync -avhP -e ssh EmilyDombrowski@agrf-data.agrf.org.au:files/AGRF_NXGSQCAGRF25090171-1_23JW2NLT4 ./ && rsync -avhP -e ssh EmilyDombrowski@agrf-data.agrf.org.au:files/AGRF_NXGSQCAGRF25090171-2_23JW2NLT4 ./`
6. Detach from tmux: Ctrl + b, then d
7. Exit VACC and come back to check in

NOTE: 2026-05-02
* Requesting 76 hours of wall time did not get approved. I resubmitted and asked for 24 hours. This immediately went through and the transfer has started. 

To do next: 
* CHECK if the files populated into the correct folders
* Create readme for the files
* Set up VPN to look at files at home

------ 

------    
<div id='id-section2'/> 

### Entry 2: 2026-05-04

After checking back into my repo, no files were loaded. I started the srun command and monitored it. Shortly after starting, it gave me the following error message: 

`VACC Error: `ssh: connect to host agrf-data.agrf.org.au port 22: Connection timed out



You can find some explanations for typical errors at this link:

            https://red.ht/support_rhel_ssh

rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]

rsync error: error in rsync protocol data stream (code 12) at io.c(228) [Receiver=3.2.5]`

I chatted with the VACC support team and they explained to me that the data is hitting a firewall: essentially, "the command is dying in Australia." The server on their end is not letting my request through. To overcome this, I need to reach out to AGRF  and add my IP address to their access list. Likely when I reach out, IT will need to be involved. The connection is timing out. The VACC sent different IP addresses to share with AGRF that can be added to an access list: 

mgmt-out.vacc.uvm.edu. (132.198.57.16)
login1.vacc.uvm.edu (132.198.57.101)
login2.vacc.uvm.edu (132.198.57.102)
login3.vacc.uvm.edu (132.198.57.103)
login4.vacc.uvm.edu (132.198.57.104)

------ 

------    
<div id='id-section3'/> 

### Entry 3: 2026-05-05
AGRF responded to communications from me about updating access to their server. Sam also mentioned that she creates a job with allocated wall time to do this sort of transfer, so I will keep that in my workflow (though the folks at the VACC mentioned it may not be necessary...I think given the amount of data, it is.)
Today, I will create another job and re-run the steps to download. 

I ran the following command in my job: 
`rsync -avhP -e ssh EmilyDombrowski@agrf-data.agrf.org.au:files/AGRF_NXGSQCAGRF25090171-1_23JW2NLT4 /netfiles/lockwood_lab/aus_mussels/data/raw/ && rsync -avhP -e ssh EmilyDombrowski@agrf-data.agrf.org.au:files/AGRF_NXGSQCAGRF25090171-2_23JW2NLT4 /netfiles/lockwood_lab/aus_mussels/data/raw/`

...and it actually connected! I was prompted to enter my AGRF password, then a new folder populated in my aus_mussels/data/raw folder. I now wonder if I will have to move the files out, but that is okay. It worked!! 

Next, I need to 
* wait for job to complete
* respond to emails from Sam and AGRF
* look up how to move files
* get the pipeline ready for the next step

------

------    
<div id='id-section4'/> 

### Entry 4: 2026-05-06
2026-05-06
Okay, so the 24 hours of wall time wasn't enough. I am going to start a new tmux session and go from there. 

1. tmux new -s genomics_download
2. `srun --time=48:00:00 --mem=4G --pty bash`
3. `rsync -avhP -e ssh EmilyDombrowski@agrf-data.agrf.org.au:files/AGRF_NXGSQCAGRF25090171-1_23JW2NLT4 /netfiles/lockwood_lab/aus_mussels/data/raw/ ; rsync -avhP -e ssh EmilyDombrowski@agrf-data.agrf.org.au:files/AGRF_NXGSQCAGRF25090171-2_23JW2NLT4 /netfiles/lockwood_lab/aus_mussels/data/raw/`
4. Type in password when prompted
5. Download has started. Detach from tmux (control b + d)
6. To reattach tomorrow: `tmux attach -t genomics_download'

------

------    
<div id='id-section5'/> 

### Entry 5: 2026-05-07

Okay, so I made some headway on my tmux dilemna. I logged into the vacc and did "tmux attach..." and was brought to an old tmux session I thought had crased over the weekend. Hm...but, upon ivestigation (and some insight from gemini ai), I have discovered that my session I started yesterday is still running, but each time I login to the VACC, I am shuttled in through a different login node. The good news is that my code is still working in the background, I verified that there are more files in my folder and the rsync command is running when I look at `top -u {my user name}`. 

So, lesson learned: tmux is a bit finnicky when on the VACC, but running a "job" ensures the continuity of the process in the background. 

------

------    
<div id='id-section6'/> 

### Entry 6: 2026-05-08
...so. The data is still transferring after 72 hours!!!! We love to see it. I still ran the necessary checks for storage space, and I re-initiated a new 48 hour job with the same rsync commands. The files are moving! Just...pretty slowly. Here's today's code

1. New tmux session `agrf_transfer` (login node 4 for reattachment)
2. `srun --time=48:00:00 --mem=4G --pty bash`
3. `rsync -avhP -e ssh EmilyDombrowski@agrf-data.agrf.org.au:files/AGRF_NXGSQCAGRF25090171-1_23JW2NLT4 /netfiles/lockwood_lab/aus_mussels/data/raw/ ; rsync -avhP -e ssh EmilyDombrowski@agrf-data.agrf.org.au:files/AGRF_NXGSQCAGRF25090171-2_23JW2NLT4 /netfiles/lockwood_lab/aus_mussels/data/raw/`
...my files are loading, password prompted, etc. Hopefully this will be the last push?????????????? Sigh sigh sigh. Signing off for the weekend. 


------ 

------    
<div id='id-section7'/> 

### Entry 7: 2026-05-11

LOL I need to stop saying "It will finally finish..." When will I learn. Another go, I logged back into login node 4 and my job has not finished. Lets go again. 

Again! 
1. New tmux session `agrf_transfer` (login node 4 for reattachment)
2. `srun --time=48:00:00 --mem=4G --pty bash`
3. `rsync -avhP -e ssh EmilyDombrowski@agrf-data.agrf.org.au:files/AGRF_NXGSQCAGRF25090171-1_23JW2NLT4 /netfiles/lockwood_lab/aus_mussels/data/raw/ ; rsync -avhP -e ssh EmilyDombrowski@agrf-data.agrf.org.au:files/AGRF_NXGSQCAGRF25090171-2_23JW2NLT4 /netfiles/lockwood_lab/aus_mussels/data/raw/`
...Is it my fault it has been taking so long?? This seems crazy. 

Tomorrow, I will plan to make my fastp script and array. That way, if I still need more time for the data, then I will be ready for the next step at least. 

------ 

------    
<div id='id-section7'/> 

### Entry 8: 2026-05-12

I woke up early today and checked in on the file download. It is going smoothly. It seems like the fiels are taking about 11 minutes to download each...

I have some notes about fastp and fastqc scripting. 

1. This should be ran as an array given the amount of data. Additionally, each sample was mapped over multiple lanes. This means, instead of the files being the traditional `*_R1.gz` and `*_R2.gz` format, they are `*L001_R1.gz` all the way through `*L008_R1.gz`...this means that I will need a sample file with all of the names. I already need to create a metadata file with this information, so

------ 

------    
<div id='id-section9'/> 

### Entry 9: 2026-05-13

I didn't make this note when I did it, but I did another 48 hour job that did not complete. It did make a new folder, which is good news. Unfortunately, I did take a hiatus when leaving the country, leading to notes for Tripp and his guest entry.

------

------    
<div id='id-section10'/> 

### Entry 10: 2026-05-14

Notes for Tripp: 

1. Configure VPN: login with netid and password: 
(let me know for duo authentification)
2. Open terminal on my computer
3. Log into vacc
4. cd /netfiles/lockwood_lab/aus_mussels/data/raw/
5. ll
...then if files do not look how I expect, ask me from there. 

------

------
<div id='id-section11'/> 

### Entry 11: 2026-05-17

Guest Entry (Tripp):

Today I checked on progress and reran rsync in Emily's stead. She says everything looks okay, but will request the data be stored on AUS servers for another week. Ran rsync command for 24 hours in raw folder. 

------

------
<div id='id-section12'/> 

### Entry 12: 2026-05-26

Checked back in on tmux; files have finished uploading. I got the following code output: 
`receiving incremental file list
AGRF_NXGSQCAGRF25090171-2_23JW2NLT4/

sent 28 bytes  received 1.56K bytes  42.35 bytes/sec
total size is 217.28G  speedup is 136,824,902.68`

So, for my next steps I need to do the following: 
* make a file with all the sample names to input into the array
* test the array on a subset of samples to make sure that it outputs what I expect
* run the fastq array
* next, trim the files based on how the visualization looks; decide if any files look strange, etc. QC. 

------

------
<div id='id-section13'/> 

### Entry 13: 2026-06-01
Today, I am going to deploy some scripts for fastp and fastq. Here is the code I used to make my parameter file: 
First, I cd'd to the trimmed folder. I pasted this code: 

```{bash, eval = FALSE}
# Clear out any old tracking files
> raw_list.txt

# Define the source path variable
RAW_DIR="/netfiles/lockwood_lab/aus_mussels/data/raw"

# Scan both subfolders for Forward reads (R1)
for f in ${RAW_DIR}/AGRF_NXGSQCAGRF25090171-1_23JW2NLT4/*_R1.fastq.gz ${RAW_DIR}/AGRF_NXGSQCAGRF25090171-2_23JW2NLT4/*_R1.fastq.gz; do
    if [ -f "$f" ]; then
        basename "$f" | cut -d'_' -f1 >> raw_list.txt
    fi
done

# Deduplicate and save the clean list of 70 samples
sort -u raw_list.txt > unique_samples.txt
rm raw_list.txt

# Display your finalized list with line numbers to verify
cat -n unique_samples.txt
```

The code output a list with 70 files. Success! For now, seeing all the files just with their sequences, I do realize what a mess I made of naming them...thankfully, now that there is a list, I can go ahead and make a metadata with better names. Which is frustrating, but it is alright. 

Next, I am making the following script into my trimmed directory: trim_array.sh

#### trim_array.sh

```
#!/bin/bash
#SBATCH --job-name=fastp_trim
#SBATCH --output=trim_%A_%a.out
#SBATCH --error=trim_%A_%a.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G
#SBATCH --time=04:00:00
#SBATCH --array=1-70

# Load the required compiler first, then load fastp
module load gcc/13.3.0-xp3epyt
module load fastp/0.23.4-mjw7rak

# Define raw data subfolders
DIR1="/netfiles/lockwood_lab/aus_mussels/data/raw/AGRF_NXGSQCAGRF25090171-1_23JW2NLT4"
DIR2="/netfiles/lockwood_lab/aus_mussels/data/raw/AGRF_NXGSQCAGRF25090171-2_23JW2NLT4"

# Because you are running from inside 'trimmed', save outputs directly here
OUT_DIR="."

# Extract the specific sample ID for this Slurm task
SAMPLE=$(sed -n "${SLURM_ARRAY_TASK_ID}p" unique_samples.txt)

echo "Processing task ID ${SLURM_ARRAY_TASK_ID}: Sample ${SAMPLE}"

# Determine which folder this specific sample lives in
if ls ${DIR1}/${SAMPLE}_* >/dev/null 2>&1; then
    DATA_DIR=$DIR1
elif ls ${DIR2}/${SAMPLE}_* >/dev/null 2>&1; then
    DATA_DIR=$DIR2
else
    echo "ERROR: Sample ${SAMPLE} not found in either folder!"
    exit 1
fi

echo "Merging 8 lanes for ${SAMPLE}..."
cat ${DATA_DIR}/${SAMPLE}_*L00*_R1.fastq.gz > ${SAMPLE}_merged_R1.fastq.gz
cat ${DATA_DIR}/${SAMPLE}_*L00*_R2.fastq.gz > ${SAMPLE}_merged_R2.fastq.gz

echo "Running fastp on ${SAMPLE}..."
fastp \
  --thread 4 \
  --in1 ${SAMPLE}_merged_R1.fastq.gz \
  --in2 ${SAMPLE}_merged_R2.fastq.gz \
  --out1 ${OUT_DIR}/${SAMPLE}_trimmed_R1.fastq.gz \
  --out2 ${OUT_DIR}/${SAMPLE}_trimmed_R2.fastq.gz \
  --html ${OUT_DIR}/${SAMPLE}_fastp.html \
  --json ${OUT_DIR}/${SAMPLE}_fastp.json \
  --qualified_quality_phred 20 \
  --length_required 30 \
  --detect_adapter_for_pe

echo "Cleaning up temporary merged files..."
rm ${SAMPLE}_merged_R1.fastq.gz ${SAMPLE}_merged_R2.fastq.gz

echo "Finished processing ${SAMPLE} safely."
```
I typed in `nano trim_array.sh` and entered this. Then, saved (control + o) and exited (control + x) and deployed a test run on the first sample: `sbatch --array=1-1 --time=00:30:00 trim_array.sh`

After running that, I got an error relating to how I loaded the fastp module...to do this better, I typed in:
`module spider fastp`, which gave me information about the exact version of fastp. I went in and changed two lines:
`# Load the required compiler first, then load fastp
module load gcc/13.3.0-xp3epyt
module load fastp/0.23.4-mjw7rak`

Next, I checked that it saved with `cat -n trim_array.sh` -- it worked!

Now, I will deploy the array again for a trial (AFTER I delete the two files it did output.)

When the sbatch job is running, I can exit the terminal and check in on progress with squeue. I will check back in a few minutes if the files worked, and go from there. 

...got another error. re-running. Seeing if it will resolve. After some trouble shooting, it seems like the nature of the error is arrising from the samples being ran accross 8 lanes. One of the lanes will be read, but it will fail to pass off. I think once I get past this step it will not be an issue, and hopefully the next files will not have these same formatting issues. 

FINAL update: 
The issue with this was that the files were not merged; the final version of the script (updated above) includes a portion that merges the files before they are analyzed. Because there are only 1.8 TB remaining of Lockwood lab space, I needed to run a command that would only allow a portion of the array to run at a time. Here is the command: `sbatch --array=1-70%5 trim_array.sh`. The %5 limits the amount of functions that are ran...even though the array has a 4 hour time allocation, it will allow everything to run without blowing out the space...or so I hope.

To do when I am done:
* Read me file with file structure and project goals to update
* Meta data file with cleaner names
* "Lock" raw folder so that nothing can be changed/over written; look up external hard drive to buy/ask Longman

------

------
<div id='id-section14'/> 

### Entry 14: 2026-06-02

Okay! Soo...my script worked up until the 37th file; then, I blew out the Lockwood Lab netfiles space. Time to move! I will be moving my data over to the scratch space. Here is the file path to scratch: 

`/gpfs2/scratch/edombro1`

Let's make some new folders and directories, then copy stuff over. There is plenty of space in scratch, but this folder is not backed up regularly. So something to keep in mind. Here's my scratch directory structure (for now):

edombro1
  - aus_mussels
    - data
      - trimmed

I will need to move the contents of my fastp run into the trimmed folder, and also produce the rest of my files that stopped running. From there, I also want to produce fastq .html files to look at quality of each of my samples. 

I oppened a tmux screen and ran the following to move...
```
rsync -avh --remove-source-files --progress /netfiles/lockwood_lab/aus_mussels/data/trimmed/* /gpfs2/scratch/edombro1/aus_mussels/data/trimmed/
```

Next, I need to go in and update my array script to complete the move for the rest of the files. 
I will change the output directory to my new `gpfs2/scratch/edombro1/aus_mussels/data/trimmed` folder, then re-launch the array.

According to Emily Longman, the next stage in which I should save things should be when the files get to be "bams." Fastq and fastp are perfect on scratch!

------

------
<div id='id-section15'/> 

### Entry 15: 2026-06-03

This morning, the rsync command I executed yesterday had finished. I came in and my files had successfully moved into my scratch folder. I changed my `trim_array.sh` script's output line to output my files into the gpfs2 folder...while the script was set up to output into the current directory `.`, I hard-coded this line just in case. 

I re-ran the array with the following command: 
`sbatch --array=32-70%5 trim_array.sh`
The files should continue populating. Additionally, this run is already producing .html files, so I do not need to do fastq as well. Great!

------

------
<div id='id-section16'/> 

### Entry 16: 2026-06-04

Today's coding session was largely based on what I have learned from my ecological genomics class: https://pespenilab.github.io/Ecological-Genomics/Fall2025/tutorials/EcoGen2025_PopGenomics3_mapping.html

I came back this morning to check on my fastp array...I still have error files for samples 32-70. Most of the males processed, all of the females processed...I. wonder what these additioinal files are. Looking at the outputs of one of the error files, there was 96% reads that have a quality score above 30. I will take it. 

Now that I look at it, it looks like...the files that all output errors are the ones that I ran yesterday. So. That is not awe inspiring. But the output in the error file does not seem like an issue? I will copy and paste the output here: 

```
cat trim_4364127_32.err 
Detecting adapter sequence for read1...
>I7_Nextera_Transposase_1 | >Trans2_rc | >I7_Nextera_Transposase_1 | >Trans2_rc
CTGTCTCTTATACACATCTCCGAGCCCACGAGAC

Detecting adapter sequence for read2...
>I5_Nextera_Transposase_1 | >Trans1_rc | >I5_Nextera_Transposase_1 | >Trans1_rc
CTGTCTCTTATACACATCTGACGCTGCCGACGA

Read1 before filtering:
total reads: 524409870
total bases: 78661480500
Q20 bases: 77545653450(98.5815%)
Q30 bases: 75123324029(95.502%)

Read2 before filtering:
total reads: 524409870
total bases: 78661480500
Q20 bases: 77803880350(98.9098%)
Q30 bases: 75570842323(96.071%)

Read1 after filtering:
total reads: 520447482
total bases: 73782806364
Q20 bases: 73381447574(99.456%)
Q30 bases: 71721875605(97.2068%)

Read2 after filtering:
total reads: 520447482
total bases: 73786963534
Q20 bases: 73253456387(99.277%)
Q30 bases: 71345017047(96.6905%)

Filtering result:
reads passed filter: 1040894964
reads failed due to low quality: 6851510
reads failed due to too many N: 89336
reads failed due to too short: 983930
reads with adapter trimmed: 169005421
bases trimmed due to adapters: 8703128448

Duplication rate: 20.932%

Insert size peak (evaluated by paired-end reads): 261

JSON report: /gpfs2/scratch/edombro1/aus_mussels/data/trimmed/C1R1-14C-D20-E1_fastp.json
HTML report: /gpfs2/scratch/edombro1/aus_mussels/data/trimmed/C1R1-14C-D20-E1_fastp.html

fastp --thread 4 --in1 C1R1-14C-D20-E1_merged_R1.fastq.gz --in2 C1R1-14C-D20-E1_merged_R2.fastq.gz --out1 /gpfs2/scratch/edombro1/aus_mussels/data/trimmed/C1R1-14C-D20-E1_trimmed_R1.fastq.gz --out2 /gpfs2/scratch/edombro1/aus_mussels/data/trimmed/C1R1-14C-D20-E1_trimmed_R2.fastq.gz --html /gpfs2/scratch/edombro1/aus_mussels/data/trimmed/C1R1-14C-D20-E1_fastp.html --json /gpfs2/scratch/edombro1/aus_mussels/data/trimmed/C1R1-14C-D20-E1_fastp.json --qualified_quality_phred 20 --length_required 30 --detect_adapter_for_pe 
fastp v0.23.4, time used: 2885 seconds
```

In this code, I see `JSON report: /gpfs2/scratch/edombro1/aus_mussels/data/trimmed/C1R1-14C-D20-E1_fastp.json`: however, when I look in my directory, I am not seeing this. Let me poke around...maybe I just put things in a strange file path when I hard coded the output. 

I changed my array header to include an email notification step: 
`#SBATCH --mail-type=ALL` so that I will recieve email notifications about my submitted tasks. 

...on second thought, when I look at the files, it seems like there might be an appropriate amount of them. I will write some code to check the unique file names vs. the outputs to ensure everything is on track. 

I have: 
- unique file text
- file names in the format {sample name}_trimmed_r{#}.fastq.gz

Perhaps a for loop that outputs a "yes," or "no," for every file that is in the correct format. I will need to use variables and inputs from the unique list to format this. I also think that this will be a useful documentatoin step as I go: each file successfully output (x) step, because manually checking the 70 files each time will be quite strenuous and error prone. 

```
#!/bin/bash

# Path to your file containing the unique sample prefixes
SAMPLE_LIST="unique_samples.txt"

# Directory where your trimmed fastq.gz files are stored 
# (Change "." to the actual path if they are in a different folder)
OUTPUT_DIR="."

echo "========================================="
echo "   Trimmed File Verification Report"
echo "========================================="

# Loop through each unique sample name in the text file
while IFS= read -r sample || [[ -n "$sample" ]]; do
    # Skip empty lines if any exist in the file
    [ -z "$sample" ] && continue

    # Define the expected filenames for both pairs
    R1_FILE="${OUTPUT_DIR}/${sample}_trimmed_R1.fastq.gz"
    R2_FILE="${OUTPUT_DIR}/${sample}_trimmed_R2.fastq.gz"

    # Check if both files exist
    if [[ -f "$R1_FILE" && -f "$R2_FILE" ]]; then
        echo "[ X ] $sample : Both r1 and r2 found."
    elif [[ -f "$R1_FILE" ]]; then
        echo "[ ! ] $sample : MISSING r2 file!"
    elif [[ -f "$R2_FILE" ]]; then
        echo "[ ! ] $sample : MISSING r1 file!"
    else
        echo "[   ] $sample : NO trimmed files found."
    fi

done < "$SAMPLE_LIST"

echo "========================================="
```

...okay so they all ran and I am just clueless. Woo!

Next step: 
* download the reference genome for mapping
* make sure bwa-mem2 will be downloaded for mapping (`module spider bwa-mem2`), and check out some of the documentation. 
* Map to reference

This should be the command to download the reference genome. 

`wget "ftp.ncbi.nlm.nih.gov/genomes/all/GCF/965/363/235/GCF_965363235.1_xbMytGall1.hap1.1/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna.gz"`

This part was actually less straightforward than I imagined. I had a reference genome picked out from a paper, but when I went to NCBI, there were multiple choices for references. Intriguing! From there, I saw that NCBI had a reference with a checkmark next to it that was designated as *the* reference genome. Alright. I chatted with Gwen, and she explained that that genome is good because it is haplotype phased...I had never heard this term before. 

Here is a website and a video link that provide some interesting schematics and explanations: https://www.pacb.com/blog/ploidy-haplotypes-and-phasing/; https://www.youtube.com/watch?v=15NPZCGP_e4
From consulting these, I now understand that phasing helps elucidate haplotype blocks inherited from the mother and the father more clearly than unphased data. I wonder why that would be prefereable in a reference genome, where this reference mussel is not related directly to any of my samples? 
-> from a reddit user...lol not amazing source but anyway...phased genomes may give better data for any imputation that occurs. This is a compelling reason for me to use it other than "it seems better."

To get this link, I copied the url for the website of the reference I chose (starting at ftp. and deleting the https:/) then, copied the .fna file string lower on the website. This was not inutitive, so hopefully this note will help me in the future. 

```
#!/bin/bash
#SBATCH --job-name=download_ref
#SBATCH --partition=short
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --time=00:30:00
#SBATCH --output=download_%j.out
#SBATCH --error=download_%j.err

# wget command from ecological genomics and reference genome from NCBI
wget "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/965/363/235/GCF_965363235.1_xbMytGall1.hap1.1/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna.gz"
```

Next, I will develop my scripts to run bwa-mem2. This program will align my fastq files with the reference that I just downloaded. 

First, I will need to make sure that the VACC has bwa-mem2 with `module spider`. From there, I will look at the commands that the command executes and search some other scripts. 
It is already on the VACC. Nice. Next, I needed to load it, then I checked its functionalities. The three comands that it output are: 
```
Usage: bwa-mem2 <command> <arguments>
Commands:
  index         create index
  mem           alignment
  version       print version number
  ```
  
Seems pretty straight forward?

 #### mapping.sh

```
#!/bin/bash
#SBATCH --job-name=bwa_map_array
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --mem=45G
#SBATCH --time=04:00:00
#SBATCH --array=1-70
#SBATCH --output=logs/map_%A_%a.out
#SBATCH --error=logs/map_%A_%a.err


# SLURM will send me an email when the job is started, finished, and submitted
#SBATCH --mail-type=ALL

# This is a script for mapping my mussel samples to the Mytilus galloprovincialis reference genome. 

# ------------------------------------------------------------------
# 1. ENVIRONMENT & DIRECTORIES
# ------------------------------------------------------------------
# Load bwa-mem2 - the most up to date version as of June 2026
module load bwa-mem2/2.2.1

SAMPLE_LIST="/gpfs2/scratch/edombro1/aus_mussels/data/trimmed/unique_samples.txt"
REF_GENOME="/gpfs2/scratch/edombro1/aus_mussels/data/reference/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna"
TRIM_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/trimmed"
OUT_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/mapped"

# errors will output in the logs folder that is inside the mapped folder - see sbatch header

# ------------------------------------------------------------------
# 2. MATCH SLURM TASK ID TO SAMPLE NAME
# ------------------------------------------------------------------
# Extract the specific line from the unique sample text file matching this task index
NAME=$(sed -n "${SLURM_ARRAY_TASK_ID}p" ${SAMPLE_LIST})

# Print standard documentation to the .out log for auditing
echo "Processing Task ID: ${SLURM_ARRAY_TASK_ID}"
echo "Sample Name extracted: ${NAME}"
echo "Running on Node: ${SLURMD_NODENAME}"

# ------------------------------------------------------------------
# 3. DEFINE INPUTS/OUTPUTS & RUN MAPPING
# ------------------------------------------------------------------
# Match your trimmed filename format
READ1="${TRIM_DIR}/${NAME}_trimmed_R1.fastq.gz"
READ2="${TRIM_DIR}/${NAME}_trimmed_R2.fastq.gz"
OUT_SAM="${OUT_DIR}/${NAME}.sam"

# Execute bwa-mem2 utilizing the 10 cpus requested from Slurm
bwa-mem2 mem -t 10 ${REF_GENOME} ${READ1} ${READ2} > ${OUT_SAM}

echo "Mapping complete for ${NAME}."
```

bwa-mem2 can have issues based on which VACC node it is ran on; Gwen has ran into this, and upon checking out the VACC documentation website, https://www.uvm.edu/vacc/docs/start_guide/running_jobs/ it seems that when you request a node for the job, your stuff will get submitted to the first available node. Not all nodeas have the hardware to support bwa-mem2 (or at least that is our working hypothesis that Benett at the VACC will confirm or deny). 

I will run a trial array, then move on depending on the output: 
`sbatch --array=1-1 mapping.sh` 

...it wrote out a .sam that was 0 in length. I will come back to this later! I tried! 

------

------
<div id='id-section17'/> 

### Entry 17: 2026-06-05

Today, I am going to:
1. Index the reference genome
2. Correct my array script so that it runs better
3. Set up code to check that all of my files go through the mapping script

1. Index the reference genome
So, Gwen's hypothesis was confirmed: bwa-mem2 can only run on VACC nodes with specific processors. I ran the command `show_node_restraints`, which output: 
```
The following are all the currently available constraints and the nodes
to which they apply.

NODELIST               AVAIL_FEATURES
node[250-258]          10g, cascadelake, intel, noib
node[300-311,314-338]  epyc_7763, amd, ib, ib1
node[400-420]          epyc_9654, amd, ib, ib2
node[500-516]          amd, ib, ib3
hc-node[01-02]         epyc_7F52, amd, hc, ib
shared1                epyc_7543
hgnode[01-02]          GPU_SKU:H100_SXM, GPU_SKU:H100, GPU_GEN:HOPPER, GPU_FP:FP32, GPU_FP:FP64, GPU_MEM:80GB, GPU_CC:9.0, GPU_ANY, h100
h2xnode[01-05]         GPU_SKU:H200_SXM, GPU_SKU:H200, GPU_GEN:HOPPER, GPU_FP:FP32, GPU_FP:FP64, GPU_MEM:140GB, GPU_CC:9.0, GPU_ANY
h2node[01-16]          GPU_SKU:H200_NVL, GPU_SKU:H200, GPU_GEN:HOPPER, GPU_FP:FP32, GPU_FP:FP64, GPU_MEM:140GB, GPU_CC:9.0, GPU_ANY, h200
r6node[01-06]          GPU_SKU:RTX6000, GPU_GEN:BLACKWELL, GPU_FP:FP32, GPU_MEM:96GB, GPU_CC:12.0, GPU_ANY
gpunode001             GPU_SKU:A100, GPU_GEN:AMPERE, GPU_FP:FP32, GPU_FP:FP64, GPU_MEM:40GB, GPU_CC:8.0, GPU_ANY, a100
```

Upon consulting with AI...it seems that : "The AMD nodes (node[300-338] and node[400-420]) run on epyc_7763 (Zen 3) and epyc_9654 (Zen 4) processors. Zen 4 architecture (epyc_9654, which are nodes 400 to 420) natively supports the full suite of AVX-512 instructions—including AVX512BW!"...alright, so I will run subsequent jobs that are on these nodes. 

First, the indexing step: 
* cd into my reference folder
* tmux: `tmux new -s index`
* `srun --partition=general --constraint=ib1 --cpus-per-task=1 --mem=150G --time=05:00:00 --pty bash`
* `module load bwa-mem2/2.2.1` 
# * `gunzip GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna.gz` <- THIS WAS UNNEEDED <- the reference must be unzipped for this step and future steps. The mapping.sh script will also reference the unzipped file. When I ran this command, it did not also save the zipped file...it just overwrote it with the unzipped one. 
* `bwa-mem2 index GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna`

When I ran that command, I got the following output: 
`Looking to launch executable "/gpfs1/sw/rh9/pkgs/bwa-mem2/2.2.1/bwa-mem2.avx512bw", simd = .avx512bw
Launching executable "/gpfs1/sw/rh9/pkgs/bwa-mem2/2.2.1/bwa-mem2.avx512bw"

Please verify that both the operating system and the processor support Intel(R) X87, CMOV, MMX, FXSAVE, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, MOVBE, POPCNT, F16C, AVX, FMA, BMI, LZCNT, AVX2, AVX512DQ, AVX512F, ADX, AVX512CD, AVX512BW, AVX512VL and CLWB instructions.`
So...no progress, exactly. Gwen will imminently share with me how she successfully ran this. I am hopeful that I can start the indexing today and get the rest of the steps done by this weekend...tbd.

2. Update my array script
Gwen gave me these lines that she included in her sbatch header that made her files run: 
```
#SBATCH -t 20:00:00
#SBATCH --constraint=ib1
```

So, I will put these into my mapping.sh file from yesterday: 

#### mapping.sh (updated with constraints)

```
#!/bin/bash
#SBATCH --job-name=bwa_map_array
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --mem=50G
#SBATCH --time=04:00:00
#SBATCH --constraint=ib1
#SBATCH --array=1-70
#SBATCH --output=/gpfs2/scratch/edombro1/aus_mussels/data/mapped/logs/map_%A_%a.out
#SBATCH --error=/gpfs2/scratch/edombro1/aus_mussels/data/mapped/logs/map_%A_%a.err


# SLURM will send me an email when the job is started, finished, and submitted
#SBATCH --mail-type=ALL

# This is a script for mapping my mussel samples to the Mytilus galloprovincialis reference genome. 

# ------------------------------------------------------------------
# 1. ENVIRONMENT & DIRECTORIES
# ------------------------------------------------------------------
# Load bwa-mem2 - the most up to date version as of June 2026
module load bwa-mem2/2.2.1

SAMPLE_LIST="/gpfs2/scratch/edombro1/aus_mussels/data/trimmed/unique_samples.txt"
REF_GENOME="/gpfs2/scratch/edombro1/aus_mussels/data/reference/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna"
TRIM_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/trimmed"
OUT_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/mapped"

# errors will output in the logs folder that is inside the mapped folder - see sbatch header

# ------------------------------------------------------------------
# 2. MATCH SLURM TASK ID TO SAMPLE NAME
# ------------------------------------------------------------------
# Extract the specific line from the unique sample text file matching this task index
NAME=$(sed -n "${SLURM_ARRAY_TASK_ID}p" ${SAMPLE_LIST})

# Print standard documentation to the .out log for auditing
echo "Processing Task ID: ${SLURM_ARRAY_TASK_ID}"
echo "Sample Name extracted: ${NAME}"
echo "Running on Node: ${SLURMD_NODENAME}"

# ------------------------------------------------------------------
# 3. DEFINE INPUTS/OUTPUTS & RUN MAPPING
# ------------------------------------------------------------------
# Match your trimmed filename format
READ1="${TRIM_DIR}/${NAME}_trimmed_R1.fastq.gz"
READ2="${TRIM_DIR}/${NAME}_trimmed_R2.fastq.gz"
OUT_SAM="${OUT_DIR}/${NAME}.sam"

# Execute bwa-mem2 utilizing the 10 cpus requested from Slurm
bwa-mem2 mem -t 10 ${REF_GENOME} ${READ1} ${READ2} > ${OUT_SAM}

echo "Mapping complete for ${NAME}."
```

3. Set up code to check that all of my files go through the mapping script

```
#!/bin/bash

# Path to your file containing the unique sample prefixes
SAMPLE_LIST="gpfs2/scratch/edombro1/aus_mussels/data/trimmed/unique_samples.txt"

# Directory where mapped files are stored 
OUTPUT_DIR="gpfs2/scratch/edombro1/aus_mussels/data/mapped"

echo "========================================="
echo "   Mapped File Verification Report"
echo "========================================="

# Loop through each unique sample name in the text file
while IFS= read -r sample || [[ -n "$sample" ]]; do
    # Skip empty lines if any exist in the file
    [ -z "$sample" ] && continue

    # Define the expected filenames for both pairs
    MAP_FILE="${OUTPUT_DIR}/${sample}.sam" 

    # Check if both files exist
    if [[ -f "MAP_FILE" ]]; then
        echo "[ X ] $sample : Mapped file found."
    else
        echo "[   ] $sample : NO mapped filee found."
    fi

done < "$SAMPLE_LIST"

echo "========================================="
```

------

------
<div id='id-section18'/> 

### Entry 18: 2026-06-08

I am back; I did not run anything this weekend. First thing: I need to make sure the appropriate files came out of my bwa-mem2 indexing. So, I need to do some reading on what the indexing output files should be...

So, the output files from the indexing job should be files ending with: 
* .0123
* .amb
* .ann
* .bwt.2bit.64
* .pac

It looks like I have these files, so I think that everything worked. My next step will be to launch my mapping array.

Before launching my mapping array this morning, I made the following updates and annotations to my script:

#### mapping.sh (updated and annotated)

```
#!/bin/bash
#SBATCH --job-name=bwa_map_array
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --mem=50G
#SBATCH --time=04:00:00
#SBATCH --constraint=ib1
#SBATCH --array=1-70
#SBATCH --output=/gpfs2/scratch/edombro1/aus_mussels/data/mapped/logs/map_%A_%a.out
#SBATCH --error=/gpfs2/scratch/edombro1/aus_mussels/data/mapped/logs/map_%A_%a.err

# constraint must be specified for this package to run

# SLURM will send me an email when the job is started, finished, and submitted
#SBATCH --mail-type=ALL

# This is a script for mapping my mussel samples to the Mytilus galloprovincialis reference genome. 

# ------------------------------------------------------------------
# 1. ENVIRONMENT & DIRECTORIES
# ------------------------------------------------------------------
# Load bwa-mem2 - the most up to date version as of June 2026
module load bwa-mem2/2.2.1

SAMPLE_LIST="/gpfs2/scratch/edombro1/aus_mussels/data/trimmed/unique_samples.txt"
REF_GENOME="/gpfs2/scratch/edombro1/aus_mussels/data/reference/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna"
TRIM_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/trimmed"
OUT_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/mapped"

# errors will output in the logs folder that is inside the mapped folder - see sbatch header

# ------------------------------------------------------------------
# 2. MATCH SLURM TASK ID TO SAMPLE NAME
# ------------------------------------------------------------------
# Extract the specific line from the unique sample text file matching this task index
NAME=$(sed -n "${SLURM_ARRAY_TASK_ID}p" ${SAMPLE_LIST})

# Print standard documentation to the .out log for auditing
echo "Processing Task ID: ${SLURM_ARRAY_TASK_ID}"
echo "Sample Name extracted: ${NAME}"
echo "Running on Node: ${SLURMD_NODENAME}"

# ------------------------------------------------------------------
# 3. DEFINE INPUTS/OUTPUTS & RUN MAPPING
# ------------------------------------------------------------------
# Match your trimmed filename format
READ1="${TRIM_DIR}/${NAME}_trimmed_R1.fastq.gz"
READ2="${TRIM_DIR}/${NAME}_trimmed_R2.fastq.gz"
OUT_SAM="${OUT_DIR}/${NAME}.sam"

# Execute bwa-mem2 utilizing the 10 cpus requested from Slurm; this command requires the reference genome to be indexed first (behind the scenes)
bwa-mem2 mem -t 10 ${REF_GENOME} ${READ1} ${READ2} > ${OUT_SAM}

echo "Mapping complete for ${NAME}."
```

I will run this step with the capacitor for good vacc protocol...and because I will move to other tasks and prepare future scripts from here. 

`sbatch --array=1-1 mapping.sh` 
...so, I came back to this after 3 hours. It is still going. I wonder if I will need to give it more time? I would prefer a larger margin, but also, if I run this with the capacitor, it will probably take at least a full day. Good to know before deploying it. 

The 4 hour window was not enough, so I will do it again. I'm going to remove the old files and run the whole array but with the capacitor...

`sbatch --array=1-70%5 mapping.sh`

I deployed that and have no imminent hopes of it getting done soon. So, I will be reading up on how to convert the .sam files to .bam files. I also want to do some steps to check for reference bias. I will be consulting our ecological genomics files and I even found a youtube video. 

Here is the samtool's website:
* https://www.htslib.org/doc/samtools.html

Some useful information:
- flagstat: passses through the input file and 

------

------
<div id='id-section19'/> 

### Entry 19: 2026-06-09

I must have been delusional thinking that 4 hours per file would be enough for my sequence alignment array. After checking in today, 10 hours per sample is not enough - a lot of them are timing out. I'm going to let the array run until the end of the work day, then I will stop it and purge the incomplete files by using a grep command in the error log files. 

The universe loves me, so the VACC is down tomorrow. I will wait until it is back up and re-launch my array on late Wednesday night/Thursday. 

------

------
<div id='id-section20'/> 

### Entry 20: 2026-06-11

So, my job partially kept running even while the VACC was under maintenance...cool! Still, not all of the files completely mapped. I bumped the timing in my mapping script to 24 hours and bumped up the throttle to allow 10 jobs to run at once. I cleared out the incomplete .sam files and re-started the array with the following command: 
`sbatch --array=2,3,5,7-10,12,14,15,18-20,23,26,27,32,35-70%10 mapping.sh`
to get the files that had to be re-done...about half were not properly aligning, so hopefully this will do the trick. I will report back. 

I used a loop with grep to look at the error files and identify which samples timed out in relation to their position in the array. Once I am done, I will run the loop to ensure all files have been created and double check that all ran correctly and didn't time out. This seems like it would create trouble down the line. 

Another fun thing going on for me: At this rate, I am going to blow out the scratch storage space with how big the sequence alignment files are. So, I have officially decided to use the CRAM storage technique instead of the BAM. To properly implement this without using up all of the space, I have to run these two scripts at the same time. 
The benefits to CRAM: 
* retains all the same information as a BAM file
* more compressed; can keep the same amount of storage 
Cons:
* more computationally intensive
* requires a stored copy of the reference genome

...the drawbacks are very small compared to paying thousands of dollars to store terrabytes of sequence data. So, that shall be my next step. The plan is to delete the sam files and re-write them as CRAM files. 

Here's my new script for `sam_to_cram.sh`

#### sam_to_cram.sh

```
#!/bin/bash
#SBATCH --job-name=sam2cram
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=8G
#SBATCH --time=06:00:00
#SBATCH --output=/gpfs2/scratch/edombro1/aus_mussels/data/cram/logs/cram_%a.out

# 1. LOAD REQUIRED MODULES - dependency plus sam tools
module load gcc/13.3.0-xp3epyt
module load samtools/1.19.2-pfmpoam

# 2. DEFINE FILE PATHS - reference genome, sam files, cram outputs, error log files for sams, and sample names
REF_GENOME="/gpfs2/scratch/edombro1/aus_mussels/data/reference/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna"
SAM_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/mapped"
CRAM_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/cram"
MAPPING_LOG_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/mapped/logs"
SAMPLE_LIST="/gpfs2/scratch/edombro1/aus_mussels/data/trimmed/unique_samples.txt"

# 3. FILE NAMES
# use task name and sample to name files
SAMPLE_NAME=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "${SAMPLE_LIST}")

INPUT_SAM="${SAM_DIR}/${SAMPLE_NAME}.sam"
OUTPUT_CRAM="${CRAM_DIR}/${SAMPLE_NAME}.cram"

# Grabs the Master Job ID from the command line argument you type
MAPPING_JOB_ID=$1

if [ -z "${MAPPING_JOB_ID}" ]; then
    echo "ERROR: You forgot to provide the mapping Master Job ID!" >&2
    echo "Usage: sbatch --array=ID sam_to_cram.sh <MAPPING_JOB_ID>" >&2
    exit 1
fi

# Dynamically reconstructs your exact 'map_%A_%a.err' layout from disk
MAPPING_LOG="${MAPPING_LOG_DIR}/map_${MAPPING_JOB_ID}_${SLURM_ARRAY_TASK_ID}.err"

echo "--------------------------------------------------"
echo "Slurm Array Task ID: ${SLURM_ARRAY_TASK_ID}"
echo "Processing Sample Name: ${SAMPLE_NAME}"
echo "--------------------------------------------------"

# =====================================================================
# TAILORED LOG VALIDATION: CHECKING FOR ABORT SIGNATURES IN LOG FILES
# =====================================================================
echo "Auditing original mapping log: ${MAPPING_LOG}"

if [ ! -f "${MAPPING_LOG}" ]; then
    echo "ERROR: Original mapping log file does not exist!" >&2
    echo "sam didn't complete?" >&2
    exit 1
fi

# Check for Slurm timeout kill tags or common pipeline errors
if grep -q "DUE TO TIME LIMIT" "${MAPPING_LOG}"; then
    echo "ERROR: Detected Slurm walltime timeout signature." >&2
    echo "sam didn't complete?" >&2
    exit 1
elif grep -E -iq "error|fail|sigkill|oom|out of memory" "${MAPPING_LOG}"; then
    echo "ERROR: Found failure keywords in the mapping log!" >&2
    echo "sam didn't complete?" >&2
    exit 1
fi

echo "Mapping log verified cleanly. Proceeding to compression..."

# =====================================================================
# 4. RUN LOSSLESS CRAM CONVERSION & COORDINATE SORT IN ONE STEP
# =====================================================================
echo "Compressing and coordinate-sorting SAM directly to CRAM..."

# In the original file, I used 'samtools view' 
# This version replaces that with 'samtools sort' to INDEX the files 
samtools sort -@ 2 -O CRAM --reference "${REF_GENOME}" -o "${OUTPUT_CRAM}" "${INPUT_SAM}"


# =====================================================================
# 5. INDEX THE NEW SORTED CRAM FILE
# =====================================================================
echo "Generating structural index..."

samtools index "${OUTPUT_CRAM}"


# =====================================================================
# 6. FOOLPROOF SAFETY PURGE BLOCK
# =====================================================================
# $? checks the exit status of the 'samtools index' command. 0 means perfection.
if [ $? -eq 0 ] && [ -f "${OUTPUT_CRAM}.crai" ]; then
    
    # This line calculates the size of the new .crai index file in bytes.
    INDEX_SIZE=$(stat -c%s "${OUTPUT_CRAM}.crai")
    
    # A real, healthy genomic index must be larger than 10KB (10,000 bytes).
    # If it's a tiny double-digit file, something went wrong!
    if [ "${INDEX_SIZE}" -gt 10000 ]; then
        echo "CRAM and Index verified successfully. Purging raw SAM file to save space..."
        rm "${INPUT_SAM}"
    else
        echo "CRITICAL ERROR: Index file generated, but size (${INDEX_SIZE} bytes) is suspiciously small!" >&2
        echo "Keeping raw SAM file for safety." >&2
        exit 1
    fi
else
    echo "CRITICAL ERROR: CRAM sorting or indexing failed! Keeping raw SAM file." >&2
    exit 1
fi

echo "Task ${SLURM_ARRAY_TASK_ID} (${SAMPLE_NAME}) complete!"
```

To modify permissions and allow this to work: 
`chmod +x sam_to_cram.sh`

Running the array: 
`sbatch --array=1,4,6,11,13,16,17,21,22,24,25,28,29,30,31,33,34 /gpfs2/scratch/edombro1/aus_mussels/scripts/sam_to_cram.sh 4392772`
executed from my scripts folder. 

I came back to check on my files, and the cram files have started to generate and delete the sam files, but I got this error when I checked the output files: 
```
cat cram_11.out 
--------------------------------------------------
Slurm Array Task ID: 11
Processing Sample Name: B2R1-22C-D10-E1
--------------------------------------------------
Auditing original mapping log: /gpfs2/scratch/edombro1/aus_mussels/data/mapped/logs/map_4392772_11.err
Mapping log verified cleanly. Proceeding to compression...
[E::cram_index_build_multiref] CRAM file is not sorted by chromosome / position
samtools index: failed to create index for "/gpfs2/scratch/edombro1/aus_mussels/data/cram/B2R1-22C-D10-E1.cram"
CRAM verified successfully. Purging raw SAM file to save space...
Task 11 (B2R1-22C-D10-E1) complete!
```
...so, (1) The sam files were deleted. (2) the cram files were generated. (3) BUT, they are not *indexed.* So, .cram files were generated, but I really needed the .crai files. These also did generate, but they had very low file sizes. They are not easily searchable (that is what unindexed means). I can run a loop to fix this. I went ahead and cancelled the sam_to_cram.sh script that is currently running, and I will run the following line.  

Part 1: request a new job with srun
tmux attach; cd into cram folder
`srun --partition=short --nodes=1 --ntasks=1 --cpus-per-task=4 --mem=24G --time=03:00:00 --pty /bin/bash`

Part 2: run the new job to index time
```
module load gcc/13.3.0-xp3epyt samtools/1.19.2-pfmpoam
cd /gpfs2/scratch/edombro1/aus_mussels/data/cram

REF="/gpfs2/scratch/edombro1/aus_mussels/data/reference/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna"

for cramfile in *.cram; do
    echo "----------------------------------------"
    echo "Fixing and coordinate-sorting: ${cramfile}"
    echo "----------------------------------------"

    # 1. Sort the unsorted CRAM into a temporary clean file
    samtools sort -@ 4 -O CRAM --reference "$REF" -o "sorted_${cramfile}" "${cramfile}"

    # 2. Build a real genomic index for it
    samtools index "sorted_${cramfile}"

    # 3. Double check that the new index is a real file (larger than 10KB)
    if [ -f "sorted_${cramfile}.crai" ] && [ $(stat -c%s "sorted_${cramfile}.crai") -gt 10000 ]; then
        echo "Success! Replacing old file with sorted data and index."
        mv "sorted_${cramfile}" "${cramfile}"
        mv "sorted_${cramfile}.crai" "${cramfile}.crai"
    else
        echo "ERROR fixing ${cramfile}. Leaving original intact."
        rm -f "sorted_${cramfile}" "sorted_${cramfile}.crai"
    fi
done
```

This timed out, so I started re-running the same code with a 12 hour time limit. 

I also modified my sam_to_cram.sh (above and in terminal) so that it will be ready when my new sam files are done mapping. That is all for today! I am exhausted. 

------

------
<div id='id-section21'/> 

### Entry 21: 2026-06-12

Alight. I let everything run yesterday and the following samples have finished up: 

2:B1R1-D1-E1
3:B1R2-14C-D10-E1
4:B1R2-22C-D10-E1
5:B1R2-D1-E1
7:B1R3-B2R1-22-D10-E1
8:B1R3-D1-E1
9:B1R4-D1-E1
10:B1R5-D1-E1
12:B2R1-D1-E1
14:B2R2-22C-D10-E1
15:B2R2-D1-E1
18:B2R3-D1-E1
19:B2R4-D1-E1
20:B2R6-D1-E1
23:B3R1-D1-E1
26:B3R2-D1-E1
27:B3R3-14C-D10-E1
32:C1R1-14C-D20-E1
35:C1R2-14C-D20-E1
36:C1R2-22C-D19-E1
37:C1R3-14C-D20-E1
38:C1R3-22C-D19-E1

So, today, with my modified sam_to_cram.sh script, I will run the following command to interleave and minimize space: 
`sbatch --array=2-5,7-10,12,14,15,18-20,23,26,27,32,35-38 /gpfs2/scratch/edombro1/aus_mussels/scripts/sam_to_cram.sh 4410682`

------

------
<div id='id-section22'/> 

### Entry 22: 2026-06-13

Logging on for the weekend. Let's do some stuff. Status: currently, the array is on file 60...almost done! Let's get the cram and crai files generating. 

Here's the command I will run: 
`sbatch --array=4,39-58 sam_to_cram.sh 4410682` after looking at the outputs in that have since loaded. The mapping array is almost done, sweet!

Running. We will check this monday.

------

------
<div id='id-section23'/> 

### Entry 23: 2026-06-15

Back to check in. I got an email that my array finished over the weekend. Today's goals are: 
* Launch the final sam to cram script
* read up on the best variant calling type for this data
* remove PCR duplicates

I am really hoping to have some kind of visualization by the end of the month. That is my current goal, then to have all of July to really get into the weeds and make progress towards my AMMR presentation.

I will run this in my terminal to get array numbers for files that have finished running to launch my sam to cram array.

`grep -nE "M01|M04|M05|M06|M07|M08|M09|M10|M11|M12|M2-GR-E1|M3-GR-E2" /gpfs2/scratch/edombro1/aus_mussels/data/trimmed/unique_samples.txt`

This prints the line numbers of the array items so that I know what to type into my job manager. Here is the command I will run to finish this out: 

`sbatch --array=59-70 sam_to_cram.sh 4410682`

Now, I will do some reading and scripting about picard and the best way to do variant calling. At some point, I will need to check bias towards the reference genome.

------

------
<div id='id-section24'/> 

### Entry 24: 2026-06-16

My files were all successfully converted! My current directory size is the following (using `du -sh *` command in my aus_mussels folder): 

`5.7T    data` and `9.5K    scripts`

Next, I will remove PCR duplicates using Picard on the CRAM Files. I was a bit worried that it would not work with the CRAM files or that I should have removed them using samtools earlier in my pipe line, but it looks like Picard can use these files (even when I do module spider in the terminal, it mentions it!).

```
------------------------------------------------------------------------------------------------------------------------------------------------------------
  picard: picard/3.1.1-otrgwkh
------------------------------------------------------------------------------------------------------------------------------------------------------------
    You will need to load all module(s) on any one of the lines below before the "picard/3.1.1-otrgwkh" module is available to load.
      gcc/13.3.0-xp3epyt
 
    Help:
      Picard is a set of command line tools for manipulating high-throughput
      sequencing (HTS) data and formats such as SAM/BAM/CRAM and VCF.
```

So, for this process, we are going to do .CRAM and .CRAI files -> .dedup files. I should probably make a new folder for these. Let's also start our script.

To do before implementing this script: 
* dedup folder [X]
* logs file in dedup folder [X]

Here are some links for using picard that helped me with this script: 
* https://gatk.broadinstitute.org/hc/en-us/articles/360037052812-MarkDuplicates-Picard
* https://broadinstitute.github.io/picard/

dedup.sh: 

#### dedup.sh

```
#!/bin/bash
#SBATCH --job-name=dedup
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=32G
#SBATCH --time=10:00:00
#SBATCH --output=/gpfs2/scratch/edombro1/aus_mussels/data/dedup/logs/dedup_%a.out

# this script will take an input .cram file and mark and remove 

# 1. LOAD REQUIRED MODULES - dependency plus picard, and samtools for indexing later
module load gcc/13.3.0-xp3epyt
module load picard/3.1.1-otrgwkh
module load samtools/1.19.2-pfmpoam


# 2. DEFINE FILE PATHS - reference genome, cram files, error log files, and sample names
REF_GENOME="/gpfs2/scratch/edombro1/aus_mussels/data/reference/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna"
CRAM_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/cram"
DEDUP_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/dedup"
SAMPLE_LIST="/gpfs2/scratch/edombro1/aus_mussels/data/trimmed/unique_samples.txt"

# 3. FILE NAMES - use task name and sample to name files
SAMPLE_NAME=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "${SAMPLE_LIST}")

INPUT_CRAM="${CRAM_DIR}/${SAMPLE_NAME}.cram"
DEDUP_CRAM="${DEDUP_DIR}/${SAMPLE_NAME}_dedup.cram"
METRICS_FILE="${DEDUP_DIR}/logs/${SAMPLE_NAME}_metrics.txt"

# 4. MARK AND REMOVE DUPLICATES - use java syntax and populate file names to mark and remove duplicates

echo "Starting Picard MarkDuplicates on: ${SAMPLE_NAME}"

java -Xmx28g -jar $PICARD MarkDuplicates \
      I=${INPUT_CRAM} \
      O=${DEDUP_CRAM} \
      M=${METRICS_FILE} \
      REFERENCE_SEQUENCE=${REF_GENOME} \
      REMOVE_DUPLICATES=true \
      VALIDATION_STRINGENCY=LENIENT

# 5. RE-INDEX AND CLEAN UP - requires samtools
if [ $? -eq 0 ] && [ -f "${DEDUP_CRAM}" ]; then
    echo "Picard finished successfully. Generating new matching .crai index..."
    
    # Build the brand-new index file
    samtools index "${DEDUP_CRAM}"
    
    echo "Deduplication and indexing complete for ${SAMPLE_NAME}."
else
    echo "ERROR: Picard MarkDuplicates failed or output file is missing!" >&2
    exit 1
fi

```

Running a trial: `sbatch --array 1 dedup.sh`

------


------
<div id='id-section25'/> 

### Entry 25: 2026-06-17

I came back this morning and my trial array from yesterday had finished around midnight. It seems like the 10 hour time window should be sufficient. Upon arriving, I immediately wondered how much data was output in the deduplicated file vs. original files (because I am terrified of running out of storage, as always).

It turns out that the deduplicated files actually use *more* storage than the originals; something about how the java-ran picard compresses them. For this run, for example, the original .cram file was 32G, while the dedup.cram was 35G. So, marginally bigger despite compression. Nonetheless, I am convinced that it did deduplicate the pcr copies from the data in the metrics file: 

```## htsjdk.samtools.metrics.StringHeader
# MarkDuplicates INPUT=[/gpfs2/scratch/edombro1/aus_mussels/data/cram/B1R1-14C-D10-E1.cram] OUTPUT=/gpfs2/scratch/edombro1/aus_mussels/data/dedup/B1R1-14C-D10-E1_dedup.cram METRICS_FILE=/gpfs2/scratch/edombro1/aus_mussels/data/dedup/logs/B1R1-14C-D10-E1_metrics.txt REMOVE_DUPLICATES=true VALIDATION_STRINGENCY=LENIENT REFERENCE_SEQUENCE=/gpfs2/scratch/edombro1/aus_mussels/data/reference/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 TAG_DUPLICATE_SET_MEMBERS=false REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag CLEAR_DT=true DUPLEX_UMI=false FLOW_MODE=false FLOW_QUALITY_SUM_STRATEGY=false USE_END_IN_UNPAIRED_READS=false USE_UNPAIRED_CLIPPED_END=false UNPAIRED_END_UNCERTAINTY=0 FLOW_SKIP_FIRST_N_FLOWS=0 FLOW_Q_IS_KNOWN_END=false FLOW_EFFECTIVE_QUALITY_THRESHOLD=15 ADD_PG_TAG_TO_READS=true ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 MAX_OPTICAL_DUPLICATE_SET_SIZE=300000 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
## htsjdk.samtools.metrics.StringHeader
# Started on: Tue Jun 16 15:42:53 EDT 2026

## METRICS CLASS	picard.sam.DuplicationMetrics
LIBRARY	UNPAIRED_READS_EXAMINED	READ_PAIRS_EXAMINED	SECONDARY_OR_SUPPLEMENTARY_RDS	UNMAPPED_READS	UNPAIRED_READ_DUPLICATES	READ_PAIR_DUPLICATES	READ_PAIR_OPTICAL_DUPLICATES	PERCENT_DUPLICATION	ESTIMATED_LIBRARY_SIZE
Unknown Library	8889829	274955085	29807729	527164565	5950753	63140894	44320953	0.236637	1335212899

## HISTOGRAM	java.lang.Double
```

The percent duplication was 0.236637. The run started around 4 pm and ended past midnight, indicating that the whole process tool around ~8 hours. I am hoping with the additional 4 hour buffer, all the samples should run. An interesting stat to pull from these files will be the percent duplication accross all runs; I bet using the grep and sed commands I can output a file with that info for reporting. 

Given the array's successful run, I will launch the whole thing. The current cram directory is taking up 1.8 Tb. I suspect this will come out to around ~2 Tb with the extra few gigs and metric files for each run. There is sufficient room in scratch to run this (we are currently using 6.6 Tb out of 15).

`sbatch --array=2-70%10 dedup.sh`


Running as of 11:25 am. Will check back in. 

------

------
<div id='id-section26'/> 

### Entry 26: 2026-06-22

Man, I've been dragging my feet today. 69/70 of my files ran. Before I proceed to variant calling, I need to get all of my samples ready because the software relies on all files being present.

script for a loop to check where B1R2-22C-D10-E1 fell off: 

```

# Initialize counters
missing_count=0
complete_count=0

echo "=== CHECKING mapping STATUS ==="

while IFS= read -r sample || [ -n "$sample" ]; do
    # Skip empty lines if there are any
    [ -z "$sample" ] && continue
    
    EXPECTED_FILE="/gpfs2/scratch/edombro1/aus_mussels/data/dedup/${sample}_dedup.cram"
    
    if [ ! -f "$EXPECTED_FILE" ]; then
        echo "❌ MISSING: ${sample}"
        ((missing_count++))
    else
        ((complete_count++))
    fi
done < "/gpfs2/scratch/edombro1/aus_mussels/data/trimmed/unique_samples.txt"

echo "-------------------------------------"
echo "✅ Complete: ${complete_count} / 70"
echo "❌ Missing:  ${missing_count} / 70"
=== CHECKING DEDUPLICATION STATUS ===
❌ MISSING: B1R2-22C-D10-E1
-------------------------------------
✅ Complete: 69 / 70
❌ Missing:  1 / 70

```

So, my next step is to track down this sample. It was turned into a .cram file but not a .crai file. Here is my old loop with edits to fix this: 


request interactive job in tmux:

```
srun --partition=general --nodes=1 --ntasks=1 --cpus-per-task=4 --mem=24G --time=04:00:00 --pty /bin/bash
```

Modified loop without cycling through all files:
```

module load gcc/13.3.0-xp3epyt samtools/1.19.2-pfmpoam
cd /gpfs2/scratch/edombro1/aus_mussels/data/cram

REF="/gpfs2/scratch/edombro1/aus_mussels/data/reference/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna"

for cramfile in B1R2-22C-D10-E1.cram; do
    echo "----------------------------------------"
    echo "Fixing and coordinate-sorting: ${cramfile}"
    echo "----------------------------------------"

    # 1. Sort the unsorted CRAM into a temporary clean file
    samtools sort -@ 4 -O CRAM --reference "$REF" -o "sorted_${cramfile}" "${cramfile}"

    # 2. Build a real genomic index for it
    samtools index "sorted_${cramfile}"

    # 3. Double check that the new index is a real file (larger than 10KB)
    if [ -f "sorted_${cramfile}.crai" ] && [ $(stat -c%s "sorted_${cramfile}.crai") -gt 10000 ]; then
        echo "Success! Replacing old file with sorted data and index."
        mv "sorted_${cramfile}" "${cramfile}"
        mv "sorted_${cramfile}.crai" "${cramfile}.crai"
    else
        echo "ERROR fixing ${cramfile}. Leaving original intact."
        rm -f "sorted_${cramfile}" "sorted_${cramfile}.crai"
    fi
done

```

------

------
<div id='id-section27'/> 

### Entry 27: 2026-06-23

I came back this morning to check in on my scripts. Bad news, the original cram file ran into an issue, so this did not run. All good! Here's the output from my run yesterday: 
```
for cramfile in B1R2-22C-D10-E1.cram; do
    echo "----------------------------------------"
    echo "Fixing and coordinate-sorting: ${cramfile}"
    echo "----------------------------------------"

    # 1. Sort the unsorted CRAM into a temporary clean file
    samtools sort -@ 4 -O CRAM --reference "$REF" -o "sorted_${cramfile}" "${cramfile}"

    # 2. Build a real genomic index for it
    samtools index "sorted_${cramfile}"

    # 3. Double check that the new index is a real file (larger than 10KB)
    if [ -f "sorted_${cramfile}.crai" ] && [ $(stat -c%s "sorted_${cramfile}.crai") -gt 10000 ]; then
        echo "Success! Replacing old file with sorted data and index."
        mv "sorted_${cramfile}" "${cramfile}"
        mv "sorted_${cramfile}.crai" "${cramfile}.crai"
    else
        echo "ERROR fixing ${cramfile}. Leaving original intact."
        rm -f "sorted_${cramfile}" "sorted_${cramfile}.crai"
    fi
done
----------------------------------------
Fixing and coordinate-sorting: B1R2-22C-D10-E1.cram
----------------------------------------
samtools sort: truncated file. Aborting
[E::hts_open_format] Failed to open file "sorted_B1R2-22C-D10-E1.cram" : No such file or directory
samtools index: failed to open "sorted_B1R2-22C-D10-E1.cram": No such file or directory
ERROR fixing B1R2-22C-D10-E1.cram. Leaving original intact.
[edombro1@node305 cram]$ [2026-06-22T21:36:33.021] error: *** STEP 4466596.0 ON node305 CANCELLED AT 2026-06-22T21:36:33 DUE TO TIME LIMIT ***
srun: Job step aborted: Waiting up to 302 seconds for job step to finish.
srun: error: node305: task 0: Killed
```

So, here's the game plan: 
* Remake the .cram file
* index the .cram file
* deduplicate the .cram file

From there, all samples should be ready to move on to the next stage of getting turned into a bcf file. 

Alright, so first I will have to request some wall time for this process. From what I remember, sam_to_cram.sh had to be modified for a 12 hour time limit. Next, cram to crai needed about 4 hours. And last, deduplication needed 10 hours. For all three of these processes, I will allocate around 26 hours...hopefully that will be more than enough. 

This is also great because it gives me the chance to actually assimilate all the things I've learned so far and optimize the process for if/when I work with this kind of data again. 

Here's my 'sam_cram_crai_dedup.sh' script:

#### sam_cram_crai_dedup.sh

```
#!/bin/bash
#SBATCH --job-name=sam_cram_crai_dedup
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --time=26:00:00
#SBATCH --output=/gpfs2/scratch/edombro1/aus_mussels/data/dedup/logs/dedup_%a.out

# This is a script to compress and remove pcr duplicates from a sam script. 
# Input files: .sam
# Output files: . cram, .crai, and _dedup.cram

# 1. LOAD REQUIRED MODULES - dependency plus sam tools and 
module load gcc/13.3.0-xp3epyt
module load samtools/1.19.2-pfmpoam
module load picard/3.1.1-otrgwkh

# 2. DEFINE FILE PATHS - reference genome, cram files, error log files, and sample names
REF_GENOME="/gpfs2/scratch/edombro1/aus_mussels/data/reference/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna"
SAM_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/mapped"
DEDUP_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/dedup"
SAMPLE_LIST="/gpfs2/scratch/edombro1/aus_mussels/data/trimmed/unique_samples.txt"

# 3. FILE NAMES - use task name and sample to name files
SAMPLE_NAME=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "${SAMPLE_LIST}")

INPUT_SAM="${SAM_DIR}/${SAMPLE_NAME}.sam"
TEMP_SORTED_BAM="${DEDUP_DIR}/${SAMPLE_NAME}_temp_sorted.bam"
DEDUP_CRAM="${DEDUP_DIR}/${SAMPLE_NAME}_dedup.cram"
METRICS_FILE="${DEDUP_DIR}/logs/${SAMPLE_NAME}_metrics.txt"

# 4. Sort .sam file
# Picard cannot run on the unsorted sam
samtools sort -@ 4 -O BAM -o "${TEMP_SORTED_BAM}" "${INPUT_SAM}"

# 5. MARK AND REMOVE DUPLICATES - use java syntax and populate file names to mark and remove duplicates
# .sam -> _temp.bam -> dedup.cram

echo "Starting Picard MarkDuplicates on: ${SAMPLE_NAME}"

java -Xmx28g -jar $PICARD MarkDuplicates \
      I=${TEMP_SORTED_BAM} \
      O=${DEDUP_CRAM} \
      M=${METRICS_FILE} \
      REFERENCE_SEQUENCE=${REF_GENOME} \
      REMOVE_DUPLICATES=true \
      VALIDATION_STRINGENCY=LENIENT

# 6. RE-INDEX AND CLEAN UP - requires samtools
if [ $? -eq 0 ] && [ -f "${DEDUP_CRAM}" ]; then
    echo "Picard finished successfully. Generating new matching .crai index..."
    
    # Build the brand-new index file
    samtools index "${DEDUP_CRAM}"

    echo "Deduplication and indexing complete for ${SAMPLE_NAME}."
else
    echo "ERROR: Picard MarkDuplicates failed or output file is missing!" >&2
    exit 1
fi

# 7. REMOVE TEMPORARY AND REDUNDANT FILES

rm -f "${TEMP_SORTED_BAM}"

if [ -f "${DEDUP_CRAM}.crai" ] && [ $(stat -c%s "${DEDUP_CRAM}.crai") -gt 10000 ]; then
    echo "SUCCESS: Deduplicated CRAM and Index verified successfully."
    echo "Purging raw SAM file to save space..."
    rm -f "${INPUT_SAM}"
else
    echo "CRITICAL ERROR: Index file is missing or too small! Keeping SAM." >&2
    exit 1
fi
```

Alright; now that the script exists, I will go ahead and run it on its one file.

Sanity check for what number in the array this file is: 
`cat -n unique_samples.txt: 4	B1R2-22C-D10-E1`

So to run this, I will go to scripts and run: 
`sbatch --array=4 sam_cram_crai_dedup.sh`

Alright, running. Next step: building a bcf tools script.

Here's the versions and dependencies I will need: 

```
gcc/13.3.0-xp3epyt # dependency
bcftools/1.19-iq5mwek # most updated version on VACC
```

Here's the commands: 
```
Program: bcftools (Tools for variant calling and manipulating VCFs and BCFs)
Version: 1.19 (using htslib 1.19.1)

Usage:   bcftools [--version|--version-only] [--help] <command> <argument>

Commands:

 -- Indexing
    index        index VCF/BCF files

 -- VCF/BCF manipulation
    annotate     annotate and edit VCF/BCF files
    concat       concatenate VCF/BCF files from the same set of samples
    convert      convert VCF/BCF files to different formats and back
    head         view VCF/BCF file headers
    isec         intersections of VCF/BCF files
    merge        merge VCF/BCF files files from non-overlapping sample sets
    norm         left-align and normalize indels
    plugin       user-defined plugins
    query        transform VCF/BCF into user-defined formats
    reheader     modify VCF/BCF header, change sample names
    sort         sort VCF/BCF file
    view         VCF/BCF conversion, view, subset and filter VCF/BCF files

 -- VCF/BCF analysis
    call         SNP/indel calling
    consensus    create consensus sequence by applying VCF variants
    cnv          HMM CNV calling
    csq          call variation consequences
    filter       filter VCF/BCF files using fixed thresholds
    gtcheck      check sample concordance, detect sample swaps and contamination
    mpileup      multi-way pileup producing genotype likelihoods
    roh          identify runs of autozygosity (HMM)
    stats        produce VCF/BCF stats

 -- Plugins (collection of programs for calling, file manipulation & analysis)
    39 plugins available, run "bcftools plugin -lv" to see a complete list

 Most commands accept VCF, bgzipped VCF, and BCF with the file type detected
 automatically even when streaming from a pipe. Indexed VCF and BCF will work
 in all situations. Un-indexed VCF and BCF and streams will work in most but
 not all situations.
 ```
 
 It looks like I will be using `mpileup`. For now, I am consulting a preprint from the Pespeni lab to orient myself a bit: https://www.biorxiv.org/content/biorxiv/early/2026/02/17/2026.01.20.700628.full.pdf
"Evidence of Adaptation in Structural Variants among Wild Populations of the purple sea urchin, Strongylocentrotus purpuratus"

They used mpileup and different "scaffolds," in their reference, which likely correspond to chromosomes. Let's check out my reference genome and see what underlying structure is in there. 

```
sort -k2,2rn GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna.fai | head -n 30

# column structure: contig name; length in base pairs; starting place in file; line bases; line width
NC_134838.1	133122103	102	80	81 # 1
NC_134839.1	115872679	134786334	80	81 # 2
NC_134840.1	112047329	252107524	80	81 # 3
NC_134841.1	104860103	365555547	80	81 # 4
NC_134842.1	102992780	471726504	80	81 # 5
NC_134843.1	102858672	576006796	80	81 # 6 
NC_134844.1	98048912	680151304	80	81 # 7
NC_134845.1	97139405	779425930	80	81 # 8
NC_134846.1	94721750	877779680	80	81 # 9
NC_134847.1	91363364	973685555	80	81 # 10
NC_134848.1	86550376	1066191065	80	81 # 11
NC_134849.1	81349889	1153823424	80	81 # 12
NC_134850.1	74365144	1236190290	80	81 # 13
NC_134851.1	73464853	1311485102	80	81 # 14
NW_027467982.1	267333	1385868401	80	81 # huge drop off in size past the 14th chromosome
NW_027467983.1	245216	1386139211	80	81
NW_027467984.1	225351	1386387628	80	81
NW_027467985.1	219641	1386615931	80	81
NW_027467986.1	218316	1386838453	80	81
NW_027467987.1	195018	1387059633	80	81
NW_027467988.1	186199	1387257224	80	81
NW_027467989.1	182790	1387445886	80	81
NW_027467990.1	171464	1387631096	80	81
NW_027467991.1	164758	1387804839	80	81
NW_027467992.1	153732	1387971792	80	81
NW_027467993.1	136734	1388127581	80	81
NW_027467994.1	131488	1388266160	80	81
NW_027467995.1	131459	1388399427	80	81
NW_027467996.1	128680	1388532665	80	81
NW_027467997.1	125125	1388663089	80	81
```

It looks like 98% of the assembly is on the 14 main scaffolds. I ran these lines of code to create a new .txt document with the chromosome names:

`# Extract only the names of the top 14 largest scaffolds into a list
sort -k2,2rn GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna.fai | head -n 14 | cut -f1 > primary_chromosomes.txt` 
It is located in my reference folder. 

I was poking around in Csenge's directory and found a really nicely formatted multiqc file. I want this type of visualization. Here is a link to the github

https://github.com/PespeniLab/urchin_local_adapt_WGS/blob/main/From_raw_reads_to_SNPs.md

, and here is the `multiqc.sh` script I will run: 

#### multiqc.sh

```bash
#!/bin/bash
#SBATCH --job-name=multiqc
#SBATCH --output=multiqc_%j.out
#SBATCH --error=multiqc_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=4G
#SBATCH --time=00:20:00
#SBATCH --partition=short

# script to visualize all fastq files at the same time

module load gcc/13.3.0-xp3epyt
module load py-multiqc/1.15-fmpaaj7

cd ~/scratch/aus_mussels/data/trimmed
multiqc .
```

------

------
<div id='id-section28'/> 

### Entry 28: 2026-06-24

In the style of the Pespeni lab's 2020 paper, I will be using bcf tool's mpileup command to get to the next stage. In Brennan et al. (2020) and a recent pre-print out of the Pespeni and Nunez labs, bcftools mpileup command is used on different "scaffolds," of the urchin genome (synonomous with "chromosomes"). In this case, I do have access to actual chromosomes level data from the mussels. I will start by doing this step and generating some figures and then see about getting advice from there...

#### bcf_mpileup.sh

```bash
#!/bin/bash
#SBATCH --job-name=bcf_mpileup
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=36G
#SBATCH --time=24:00:00
#SBATCH --array=1-14
#SBATCH --output=~/scratch/edombro1/aus_mussels/data/bcf/logs/call_%a.out

# this is a script that will take deduplicated .cram files and put them into a bcf file
# inputs: {sample}_dedup.cram files; .txt file with chromosome names; .txt file with .cram names
# outputs: bcf file (bianary variant call file)

# the size of my data set (70 samples with 70x coverage) means that it will be easier to parallelize this and break it up into distinct chromosomes

# 1. LOAD MODULES - dependency + bcftools
module load gcc/13.3.0-xp3epyt
module load bcftools/1.19-w67pmsz

# 2. FILE PATHS - reference, variant directory (where outputs from this script will go), list of chromosomes, and txt file with cram names
REF="/gpfs2/scratch/edombro1/aus_mussels/data/reference/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna"
VAR_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/variants"
CHROM_LIST="/gpfs2/scratch/edombro1/aus_mussels/data/reference/primary_chromosomes.txt"
CRAM_LIST="${VAR_DIR}/all_dedup_crams.txt"

# 3. IDENTIFY THIS TASK'S CHROMOSOME
CHROM_NAME=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "${CHROM_LIST}")
OUTPUT_BCF="${VAR_DIR}/split_bcfs/${CHROM_NAME}_raw.bcf"

echo "Task ID ${SLURM_ARRAY_TASK_ID}: Initiating joint variant calling on ${CHROM_NAME}"

# 4. EXPLICIT JOINT CALLING WITH HIGH-DEPTH OVERRIDES
# -d 10000 ensures all ~4900 maximum layers of experimental depth are safely processed
# -a FORMAT/AD,FORMAT/DP extracts exact allele depths for downstream delta-p tracking
bcftools mpileup --threads 2 \
    -d 10000 \
    -f "${REF}" \
    -r "${CHROM_NAME}" \
    -b "${CRAM_LIST}" \
    -a FORMAT/AD,FORMAT/DP \
    -OU | \
bcftools call --threads 2 \
    -f GQ,GP \
    -m \
    -v \
    -Ob \
    -o "${OUTPUT_BCF}"

# 5. RE-INDEX FOR SPEEDY RE-CONCATENATION
if [ $? -eq 0 ] && [ -f "${OUTPUT_BCF}" ]; then
    echo "SUCCESS: Completed variant calling for ${CHROM_NAME}. Generating index..."
    bcftools index "${OUTPUT_BCF}"
else
    echo "CRITICAL ERROR: Variant calling failed on chromosome ${CHROM_NAME}!" >&2
    exit 1
```

Before launching this script, I made a new directory with the following folder structures: 
- variants
  --logs
  --split_bcfs
  
I generated the files with chromosome names and all of the deduplicated cram names as well. See following code for example:
`ls -d /gpfs2/scratch/edombro1/aus_mussels/data/dedup/*_dedup.cram > all_dedup_crams.txt`

Alright...let's give it a go? It is running. Will check back in tomorrow and see how it is going! Super exciting...

------

------
<div id='id-section29'/> 

### Entry 29: 2026-06-29

It has been a few days. Essentially, when I checked back on Friday, there had been some issues with my script. Namely, it did not run and it produced a new `~` folder within my scripts. This is not good because it takes me on a round about journey through my directories...I need to solve this within the script and find a way to clean up this extra directory. Additionally, Danny shared his github with me, which should be useful for future things. 

Link to Danny's github: https://github.com/DanielSadler96/IntertidalSeaScapeGenomics/tree/main/Assembly

When I navigate into my new, weird directory and check the logs from my last run, here is the message that I get: 

```bash
The following module(s) are unknown:
"bcftools/1.19-w67pmsz"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "bcftools/1.19-w67pmsz"

Also make sure that all modulefiles written in TCL start with the string
#%Module
```

I'm fairly certain I got the bcftools version from module spider; let's double check.

Here's the version that it gives me for spider: `bcftools/1.19-iq5mwek`

Okay, so my code must have gotten copied over from somewhere else and the version numbers are different. Easy fix! We can work with that. 

So, I deleted the incorrect `~` directory using the open on demand point and click gui...that made me feel much "safer" than the alternative of actually deleting my whole home directory on accident. Let's continue on to fix the file path and make some mods to the script. 

#### bcf_mpileup.sh (updated)

To update, I: 
* Fixed the file path for the logs folder (I had a folder called "bcf" that doesn't exist in a path...)
* Increased the amount of time from 24-48 hours; amount of memory from 36-40
* changed the bcftools version to the proper one...
* add email to header 
* after looking at Danny's mpileup code, I added a filter step ` -q 20 \`
* Ou case was wrong
* -f has been changed to -a


```bash
#!/bin/bash
#SBATCH --job-name=bcf_mpileup
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=40G
#SBATCH --time=48:00:00
#SBATCH --array=1-14
#SBATCH --output=/gpfs2/scratch/edombro1/aus_mussels/data/variants/logs/call_%a.out
#SBATCH --mail-type=ALL

# this is a script that will take deduplicated .cram files and turn them into a bcf file
# inputs: {sample}_dedup.cram files; .txt file with chromosome names; .txt file with .cram names
# outputs: bcf file (bianary variant call file)

# the size of my data set (70 samples with 70x coverage) means that it will be easier to parallelize this and break it up into distinct chromosomes

# 1. LOAD MODULES - dependency + bcftools
module load gcc/13.3.0-xp3epyt
module load bcftools/1.19-iq5mwek

# 2. FILE PATHS - reference, variant directory (where outputs from this script will go), list of chromosomes, and txt file with cram names
REF="/gpfs2/scratch/edombro1/aus_mussels/data/reference/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna"
VAR_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/variants"
CHROM_LIST="/gpfs2/scratch/edombro1/aus_mussels/data/reference/primary_chromosomes.txt"
CRAM_LIST="${VAR_DIR}/all_dedup_crams.txt"

# 3. IDENTIFY THIS TASK'S CHROMOSOME
CHROM_NAME=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "${CHROM_LIST}")
OUTPUT_BCF="${VAR_DIR}/split_bcfs/${CHROM_NAME}_raw.bcf"

echo "Task ID ${SLURM_ARRAY_TASK_ID}: Initiating joint variant calling on ${CHROM_NAME}"

# 4. EXPLICIT JOINT CALLING WITH HIGH-DEPTH OVERRIDES
# -d 10000 ensures all ~4900 maximum layers of experimental depth are safely processed
# -a FORMAT/AD,FORMAT/DP extracts exact allele depths for downstream delta-p tracking
bcftools mpileup --threads 2 \
    -d 10000 \
    -q 20 \
    -f "${REF}" \
    -r "${CHROM_NAME}" \
    -b "${CRAM_LIST}" \
    -a FORMAT/AD,FORMAT/DP \
    -Ou | \
bcftools call --threads 2 \
    -a GQ,GP \
    -m \
    -v \
    -Ob \
    -o "${OUTPUT_BCF}"

# 5. RE-INDEX FOR SPEEDY RE-CONCATENATION
if [ $? -eq 0 ] && [ -f "${OUTPUT_BCF}" ]; then
    echo "SUCCESS: Completed variant calling for ${CHROM_NAME}. Generating index..."
    bcftools index "${OUTPUT_BCF}"
else
    echo "CRITICAL ERROR: Variant calling failed on chromosome ${CHROM_NAME}!" >&2
    exit 1
fi
```

I added a filtering step to keep the standards pretty high...

Alright, let's deploy? I don't see any reason why not. (I ran into some errors, but fixed them)

While that runs, I am going to make some notes for how to conver the bcf/vcf into figures. Additionally, I should do a check of my files and move some back over to netfiles for safe keeping. As far as figures go: 

* PCA
* Average coverage accross samples
* proportion correctly mapped onto chromosomes
* mapped reads/total reads
* PCA of average coverage (will need to weight observations before actually running this)
* site frequency spectra
* Fst
* Filter by MAF
* What kind of SNPs? (exons, introns, etc.)
* PCA per chromosome
* volcano plot
* proportion of m. galloprovincialis genes to planulatus gene x treatment

I found this website linked in Danny's github: https://speciationgenomics.github.io/pca/

The tutorials seem pretty promising. 

First, to go from vcf -> pca, it seems like some data transformations need to happen to remove any bias formed from linkage. The website above (and Danny) used the program plink to "prune," the data; then, eigenvectors and eigen values are produced. I always forget the difference between them, so I will summarize below: (information from Abdi and Williams, "Principal component analysis," 2010)
* Eigenvector: vector that reduces the complexity of the data through scaling, stretching, or compressing; length may be changed by transformations, but not the direction. (I think of this as the fixed axes of the PCA...what allows PCA to truly visualize complexity within the cloud of data points.)
* Eigenvalue: value associated with vector that reduces complexity of the data

Alright, so plink will be used to generate two data frames with eigenvalues and variables. From there, a PCA can be made. 

For now, I will make a meta data file that has the unique sample name and number of individuals in the sample.


------

------
<div id='id-section30'/> 

### Entry 30: 2026-06-30

Morning check in...my code is still running from yesterday (it is at about 22 hours...I'm glad that I bumped up the time for the batch job!) Oof, I'm cutting it pretty close to my PCA by the end of the month goal. Thankfully, I think I have a pretty solid foundation for understanding the next steps, so let's get into the proposed code now. 

I made my metadata file this morning with the samples and pool amounts. Maybe metadata is a misleading name because it is just pooled? However, I think I have lot's of documentation for everything, so it should be alright. 

This code is adapted from Danny's github and the website from up above. 

#### plink prune script

For citing plink: 
PLINK v1.9.0-b.7.7 64-bit (22 Oct 2024)            cog-genomics.org/plink/1.9/
(C) 2005-2024 Shaun Purcell, Christopher Chang   GNU General Public License v3

```bash
# Modify name of file before going through with this
VCF=/gpfs2/scratch/edombro1/aus_mussels/data/variants

module load plink/1.9b7.7

plink --vcf $VCF --make-bed --allow-extra-chr --out mussel_plink_filt

###filter MAF 0.05 prune LD 0.8

plink --bfile mussel_plink_filt \
  --indep-pairwise 50 5 0.2 \
  --allow-extra-chr \
  --out mussel_plink_filt_pruned


###generate pca
plink --bfile mussel_plink_filt --mind --allow-extra-chr  --extract  mussel_plink_filt_pruned.prune.in --pca 10  --out mussel_plink_filt_PCA

```

--make-bed : makes new bianary file
--allow-extra-chr ['0']   : "Permit unrecognized chromosome codes." "allow additional chromosomes beyond the human chromosome set. This is necessary as otherwise plink expects chromosomes 1-22 and the human X chromosome." 
--out : output file prefix
--bfile : specify prefix for output files
--indep-pairwise: "<window size>['kb'] <step size (variant ct)> <r^2 threshold>"

What I am wondering here is how to adequaately pick the amount to consider for linkage disequilibrium. Here is a quote from a Bierne et al. (2003) paper about linkage disequilibrium in hybrid mussels: 
"linkage disequilibria appear close to their maximum possible values, indicating a strong genetic barrier within all transition zones." 
Therefore, linkage can be an important factor when looking at *specifically* hybrid mussels; additionally, we sampled these hybrids in an area that is the beginning of the hybrid zone in Victoria. I wonder if this will produce inflated linkage compared to the whole hybrid zone? I will be sure to write this down to think about in the context of the whole system because I think it is interesting. 


------


------
<div id='id-section31'/> 

### Entry 31: 2026-07-01

Alright, the VCF code ran and I got access to my old github. Great! I have tried to reconnect that but at the moment it is taking longer than anticipated, so I will move on.

Let's check out the split bcfs: 
```
ls -lhS *.bcf
16G Jul  1 06:01 NC_134838.1_raw.bcf
15G Jun 30 23:00 NC_134842.1_raw.bcf
14G Jun 30 22:02 NC_134845.1_raw.bcf
14G Jul  1 03:26 NC_134843.1_raw.bcf
14G Jul  1 06:07 NC_134840.1_raw.bcf
14G Jun 30 22:02 NC_134844.1_raw.bcf
13G Jul  1 02:28 NC_134839.1_raw.bcf
13G Jun 30 18:41 NC_134848.1_raw.bcf
13G Jul  1 06:12 NC_134841.1_raw.bcf
13G Jun 30 20:42 NC_134847.1_raw.bcf
12G Jun 30 17:16 NC_134849.1_raw.bcf
12G Jul  1 00:00 NC_134846.1_raw.bcf
11G Jun 30 12:48 NC_134851.1_raw.bcf
9.9G Jun 30 14:46 NC_134850.1_raw.bcf
[edombro1@vacc-login4 split_bcfs]$ du -sh .
178G	.
```

All of the files populated with data, and none look suspiciously small. The 14 files correspond with the number of chromosomes within the mussels. For the next step, I need to filter these and then pass them off to an r package that will let me visualize these samples as a pca. Here's some code I'm working on to filter these samples and get them into good shape before that step: 

#### filter_vcf.sh

```bash
#!/bin/bash
#SBATCH --job-name=bcf_filter
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=40G
#SBATCH --time=10:00:00
#SBATCH --array=1-14
#SBATCH --output=/gpfs2/scratch/edombro1/aus_mussels/data/variants/logs/call_%a.out
#SBATCH --mail-type=ALL

# 1. LOAD MODULES - dependency + bcftools
module load gcc/13.3.0-xp3epyt
module load bcftools/1.19-iq5mwek

# 2. FILE PATHS - reference, variant directory (where outputs from this script will go), list of chromosomes, and txt file with cram names
CHROM_LIST="/gpfs2/scratch/edombro1/aus_mussels/data/reference/primary_chromosomes.txt"
VAR_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/variants"
SPLIT_BCF="/gpfs2/scratch/edombro1/aus_mussels/data/variants/split_bcfs"
OUTPUT_DIR="${VAR_DIR}/filt_bcfs"

# 3. IDENTIFY THIS TASK'S CHROMOSOME
CHROM_NAME=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "${CHROM_LIST}")
OUTPUT_FILT_BCF="${OUTPUT_DIR}/${CHROM_NAME}_filt.bcf"

# 4. STRINGENTLY FILTER THE SNPS FOR DOWNSTREAM ANALYSES
# maintain biallelic loci with specific coverage requirements to feed into poolfstat
bcftools view --threads 4 -v snps -m2 -M2 "${SPLIT_BCF}/${CHROM_NAME}_raw.bcf" | \
bcftools filter --threads 4 \
  -e 'QUAL < 30 || INFO/DP < 2500 || INFO/DP > 8000 || MIN(FORMAT/DP) < 20 || F_MISSING > 0.0' \
  -O b -o $"{OUTPUT_FILT_BCF}"

# 5. RE-INDEX
if [ -f "${OUTPUT_FILT_BCF}" ] && [ -s "${OUTPUT_FILT_BCF}" ]; then
    echo "SUCCESS: ${CHROM_NAME}_filt.bcf generated. Indexing now..."
    bcftools index --threads 4 "${OUTPUT_FILT_BCF}"
    echo "SUCCESS: Chromosome ${CHROM_NAME} complete and indexed."
else
    echo "CRITICAL ERROR: Filtration pipeline finished but output file is missing or empty." >&2
    exit 1
fi
```

Here's some annotation of this code: 
View: 
-v/V, --types/--exclude-types LIST     Select/exclude comma-separated list of variant types: snps,indels,mnps,ref,bnd,other [null]
-m/M, --min-alleles/--max-alleles INT  Minimum/maximum number of alleles listed in REF and ALT (e.g. -m2 -M2 for biallelic sites)

-> For subsequent analyses using poolfstat, it is important to strip complexity and maintain biallelic sites

Filter: 
-e, --exclude EXPR :Exclude sites for which the expression is true
-O, --output-type u|b|v|z[0-9]    u/b: un/compressed BCF, v/z: un/compressed VCF, 0-9: compression level [v]

To move into poolfstat, which is the software that I will use to create pcas with snps, I need to filter out indels etc. and only keep snps that match fairly strict criteria. Poolfstat does not deal in multiple alleles.

I submitted this job at 2:37 pm, so I'll see if the 10 hours was enough...next, I am going to go back and generate some scripts to look at coverage accross my samples using samtools etc. 

I initally ran that and ran into an error because my filtering was too stringent. So, I am going to do some qc on the cram files to figure out my average coverages, mapping rates, etc. before deciding these numbers. 

#### alignment_metrics_qc.sh (GO TO NEXT PARALLELIZED VERSION WITH EDITS)
This is a script that will parallize the process of two quality control steps: 1. getting coverage and depth metrics from cram files, and 2. getting mapping proportions from deduplicated crams. 

* timed out at 10 hours; had to re-run with modifications; see parallelized script in next day's entry for better script *

...I was too tired, should not have ran this

```bash
#!/bin/bash
#SBATCH --job-name=alignment_metrics_qc.sh
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=20G
#SBATCH --time=10:00:00
#SBATCH --output=/gpfs2/scratch/edombro1/aus_mussels/data/dedup/qc/logs/qc_metrics_pipeline.out
#SBATCH --mail-type=ALL

# inputs: deduplicated cram files; picard metrics files
# outputs: coverage.txt; mapping summary.txt

# 1. LOAD MODULES - samtools + dependency
module load gcc/13.3.0-xp3epyt
module load samtools/1.19

# 2. FILE PATHS - samples, deduplicated crams, metric txt logs, qu folder, and reference genome
SAMPLE_LIST="/gpfs2/scratch/edombro1/aus_mussels/data/trimmed/unique_samples.txt"
CRAM_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/dedup" 
LOGS_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/dedup/logs"
QC_OUT="/gpfs2/scratch/edombro1/aus_mussels/data/dedup/qc"
REF="/gpfs2/scratch/edombro1/aus_mussels/data/reference/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna"

# 1: CALCULATE GENOME-WIDE COVERAGE AND DEPTH USING SAMTOOLS

echo "=== Starting Samtools Coverage Computations ==="

while IFS= read -r sample || [ -n "${sample}" ]; do
    [[ -z "${sample}" || "${sample}" == \#* ]] && continue

    CRAM_FILE="${CRAM_DIR}/${sample}_dedup.cram"

    # Safeguard: Verify the CRAM file actually exists in gpfs1
    if [ ! -f "${CRAM_FILE}" ]; then
        echo "WARNING: CRAM file missing for sample ${sample} at ${CRAM_FILE}. Skipping..." >&2
        continue
    fi

    echo "Computing depth profiles for sample: ${sample}"

    # Get average coverage, mean depth, and % of genome covered per chromosome
    samtools coverage --reference "${REF}" "${CRAM_FILE}" > "${QC_OUT}/${sample}_coverage.txt"

done < "${SAMPLE_LIST}"

echo "Samtools coverage analysis complete."
echo "----------------------------------------------------"

# 2: EXTRACT MAPPING PROPORTIONS FROM PICARD METRICS

echo "=== Starting Picard Metrics Extraction ==="

# create empty .txt file to store metrics file data
MAPPING_SUMMARY="${QC_OUT}/mapping_proportions_summary.txt"

# Initialize the header row of our reproducible summary table
echo -e "Sample\tTotal_Reads\tUnmapped_Reads\tMapped_Reads\tProportion_Mapped" > "${MAPPING_SUMMARY}"

while IFS= read -r sample || [ -n "${sample}" ]; do
    [[ -z "${sample}" || "${sample}" == \#* ]] && continue

    PICARD_FILE="${LOGS_DIR}/${sample}_metrics.txt"

    # Safeguard: Verify the Picard metrics file exists
    if [ ! -f "${PICARD_FILE}" ]; then
        echo "WARNING: Picard metrics file missing for sample ${sample} at ${PICARD_FILE}. Skipping..." >&2
        continue
    fi

    # Grab the data line directly under the "LIBRARY" header block
    metrics_line=$(grep -A 1 "LIBRARY" "${PICARD_FILE}" | tail -n 1)
    
    # Process line using awk and append to master file
    echo "${metrics_line}" | awk -v s="${sample}" -F'\t' '{
        unpaired = $2;
        pairs = $3;
        unmapped = $5;
        
        total_reads = unpaired + (pairs * 2);
        mapped_reads = total_reads - unmapped;
        prop_mapped = (total_reads > 0) ? (mapped_reads / total_reads) : 0;
        
        printf "%s\t%d\t%d\t%d\t%.4f\n", s, total_reads, unmapped, mapped_reads, prop_mapped;
    }' >> "${MAPPING_SUMMARY}"

done < "${SAMPLE_LIST}"

echo "SUCCESS: Picard metrics extraction complete."
echo "Master file generated at: ${MAPPING_SUMMARY}"

```

Okay. I may have to log off for the day because my brain is not working at full speed right now...

------

------
<div id='id-section32'/> 

### Entry 32: 2026-07-02

Even with 10 hours, the alignment_metrics_qc.sh script from yesterday timed out. I am going to bump the time to 48 hours and hopefully it will finish...

Here are the files that completed: 

```
Jul 1 16:26 B1R1-14C-D10-E1_coverage.txt
Jul  1 17:00 B1R1-D1-E1_coverage.txt
Jul  1 17:29 B1R2-14C-D10-E1_coverage.txt
Jul  1 17:50 B1R2-22C-D10-E1_coverage.txt
Jul  1 18:19 B1R2-D1-E1_coverage.txt
Jul  1 18:46 B1R3-14C-D10-E1_coverage.txt
Jul  1 19:20 B1R3-B2R1-22-D10-E1_coverage.txt
Jul  1 20:00 B1R3-D1-E1_coverage.txt
Jul  1 20:33 B1R4-D1-E1_coverage.txt
Jul  1 21:06 B1R5-D1-E1_coverage.txt
Jul  1 21:20 B2R1-22C-D10-E1_coverage.txt
Jul  1 21:55 B2R1-D1-E1_coverage.txt
Jul  1 22:20 B2R2-14C-D10-E1_coverage.txt
Jul  1 22:48 B2R2-22C-D10-E1_coverage.txt
Jul  1 23:21 B2R2-D1-E1_coverage.txt
Jul  1 23:43 B2R3-14C-D10-E1_coverage.txt
Jul  2 00:01 B2R3-22C-D10-E1_coverage.txt
Jul  2 00:31 B2R3-D1-E1_coverage.txt
Jul  2 01:03 B2R4-D1-E1_coverage.txt
Jul  2 01:39 B2R6-D1-E1_coverage.txt
Jul  2 01:56 B3R1-14C-D10-E1_coverage.txt
```


Here is some code that will parallelize the whole process. It should go quicker, and I added a step to check if some files have already been ran

#### alignment_metrics_qc_array.sh

```bash
#!/bin/bash
#SBATCH --job-name=alignment_metrics_qc_array
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=10G
#SBATCH --time=08:00:00
#SBATCH --array=1-70
#SBATCH --output=/gpfs2/scratch/edombro1/aus_mussels/data/dedup/qc/logs/array_%A_%a.out
#SBATCH --mail-type=ALL

# 1. LOAD MODULES - samtools + dependencies
module load gcc/13.3.0-xp3epyt
module load samtools/1.19

# 2. FILE PATHS  - samples, deduplicated crams, qc directory, and picard logs directory
SAMPLE_LIST="/gpfs2/scratch/edombro1/aus_mussels/data/trimmed/unique_samples.txt"
CRAM_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/dedup"
QC_OUT="/gpfs2/scratch/edombro1/aus_mussels/data/dedup/qc"
LOGS_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/dedup/logs"

# 3. IDENTIFY TARGET SAMPLE PER TASK
# use sed -n p to print the array task
sample=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "${SAMPLE_LIST}")

# if sample doesn't exist, error message gets sent to log
if [ -z "${sample}" ]; then
    echo "Line ${SLURM_ARRAY_TASK_ID} is empty. Exiting."
    exit 0
fi

# .txt file gets inititated in output directory
FINAL_COVERAGE="${QC_OUT}/${sample}_coverage.txt"
INDIVIDUAL_MAPPING="${QC_OUT}/${sample}_map_stats.tmp"

# use coverage command in samtools to get mapping statistics for each sample
# CHECKPOINT: If a file exists from the earlier run, skip the heavy computation
if [ -f "${FINAL_COVERAGE}" ] && [ -s "${FINAL_COVERAGE}" ]; then
    echo "Checkpoint verified for ${sample}. Skipping samtools coverage..."
else
    if [ -f "${CRAM_DIR}/${sample}_dedup.cram" ]; then
        echo "Computing parallel coverage for: ${sample}"
        samtools coverage "${CRAM_DIR}/${sample}_dedup.cram" > "${FINAL_COVERAGE}"
    else
        echo "ERROR: CRAM missing for ${sample}" >&2
    fi
fi

# 4. EXTRACT PICARD STATS - uses grep and awk to extract coverage data
PICARD_FILE="${LOGS_DIR}/${sample}_metrics.txt"
if [ -f "${PICARD_FILE}" ]; then
    metrics_line=$(grep -A 1 "LIBRARY" "${PICARD_FILE}" | tail -n 1)
    echo "${metrics_line}" | awk -v s="${sample}" -F'\t' '{
        unpaired = $2; pairs = $3; unmapped = $5;
        total = unpaired + (pairs * 2);
        mapped = total - unmapped;
        prop = (total > 0) ? (mapped / total) : 0;
        printf "%s\t%d\t%d\t%d\t%.4f\n", s, total, unmapped, mapped, prop;
    }' > "${INDIVIDUAL_MAPPING}"
fi
```


Alright, I got my github issues reconciled and I can now push from my original account to this repo. Success! Tomorrow, I will hopefully deploy the vcf filtering script, then be on my way to some figures. Yay!

------

------
<div id='id-section33'/> 

### Entry 33: 2026-07-03

Alright, my script for metrics finished running; let's check it out. (I did technically get some errors but I got an output file. Let's check it out in R. )

I created `mapping_proportions.Rmd` to check some things out. It looks like 24 samples had pretty low mapping proportions, likely from algal contamination if I had to guess. 

I think it is a lot to take in and assimilate before I launch my bcf filtering script. I will take a walk to think about it. 

Some next steps: 
* subset coverage by adults and larvae; adults are likely driving the very high mean at the moment
* think about how algal contamination and experimental set up could have been avoided
* map algal stuff just to be sure that is what is happening

------

------
<div id='id-section34'/> 

### Entry 34: 2026-07-06

Alright, I took the weekend to decompress a bit because the mapping info has been a bit stressful...with some time and reflection, I have determined that this will be the path forward. 

* The array I ran to extract the mapping stats had a failing exit code; I need to look back at that, check it out, and see what happened. Is this contributing to the samples that have very low mapping stats? 
* Next, I need to look at the reality of how mapping stats and low mapping percentages impact the interpretibility of results: are low mapping stats an immediate throw out of the whole sample?
* I also need to chat with Brent about this, how it plays into the manuscript, and the implications. 
* Plot the mapping stats by sample: subset into adult, day 1, day 10, and final day and look at as a histogram. 

As far as getting results that were a bit stressful to me, it was very helpful to take a few days to rest and then come back instead of trying to figure out, interpret, and solve everything right there. For future reference, this is 100% the correct call and to come back with a rested, clearer head. 

* Step 1: Look at array error
Here is the error message that I got from the array: 
```
cat array_4534580_57.out 
Computing parallel coverage for: F06
[W::cram_populate_ref] Creating reference cache directory /users/e/d/edombro1/.cache/hts-ref
This may become large; see the samtools(1) manual page REF_CACHE discussion
[E::easy_errno] Libcurl reported error 92 (Stream error in the HTTP/2 framing layer)
[E::easy_errno] Libcurl reported error 92 (Stream error in the HTTP/2 framing layer)
[W::find_file_url] Failed to read reference "https://www.ebi.ac.uk/ena/cram/md5/199cfe7d0b1329ded33480c10b113839": Input/output error
/var/spool/slurm/d/job4534637/slurm_script: line 61: unexpected EOF while looking for matching ``'
/var/spool/slurm/d/job4534637/slurm_script: line 66: syntax error: unexpected end of file
```

So, on my last script, I was getting an error because I copied and pased two extra lines from my code notebook...whoops. I have changed my workflow instead to reference the title of scripts and to edit them in their own .sh files that I will reference here instead. 

I made edits to alignment_metric_qc_array.sh - before, I took out the reference from the script. Interesting behavior because the mapping requires looking at the reference...anyway, I added a pipe to the script so that samtools view can look at the reference so that it is in the memory of the computer, then samtools coverage will do the heavy lifting.

Alright, I made the changes and the first file completely ran pretty quickly for trouble shooting; however, it does not look like the mapping proportions will change at all...those were coming from picard, and therefore not impacted by the script adjustments that caused the script to fail. So, it looks like the 24 samples really are that low. 

Alright, I re-ran the array; it took less than two hours per sample, so the 12 hour time window is quite big. Next, I want to get the coverage information per sample and per chromosome/scaffold. 

------

------
<div id='id-section35'/> 

### Entry 35: 2026-07-07

Alright, today I will be doing some more things in R. I have been continuing to make updates to my mapping_proportions script, though I have not loaded in the new data that I generated yesterday; if I am going to get to a place where I can move on to my pcas, I need to get moving. Additionally, my AMMR abstract was accepted for September, so I need to continue making progress. 

Investigating further, the samples from day 1 and day 10 had very good mapping proportions (mapped reads/unmapped reads) (see box plot), while samples from days 10 and day 19/20 really dropped off. Particularly, there is a very high variance in the 22C conditions and a lower median mapping proportion. This is consistent with the hypothesis of algae contamination, as the algae would have been more likely to proliferate in the warmer temperature conditions, causing microbial shifts etc...

Anyway, moving on to coverage, here is an example head of a file that I get with the {sample}_coverage.txt files

```
head M10_coverage.txt 
#rname	startpos	endpos	numreads	covbases	coverage	meandepth	meanbaseq	meanmapq
NC_134838.1	1	133122103	74472933	121874506	91.5509	70.9874	39.5	34.4
NC_134839.1	1	115872679	68438635	110184781	95.0913	75.7152	39.5	35.5
NC_134840.1	1	112047329	62673746	103131897	92.0432	70.9654	39.5	34.9
NC_134841.1	1	104860103	60623324	99232258	94.633	74.1967	39.5	35.9
NC_134842.1	1	102992780	48433665	87102453	84.5714	58.2984	39.5	31.1
NC_134843.1	1	102858672	54890997	93151744	90.5628	67.2043	39.5	33.9
NC_134844.1	1	98048912	47857063	85919034	87.6287	60.8502	39.5	32.6
NC_134845.1	1	97139405	45589519	82617690	85.0506	58.1648	39.5	33.1
NC_134846.1	1	94721750	51812607	86902871	91.7454	69.3013	39.5	35.2
```

Let's make a summary file that extracts all this information from each sample, then with dplyr, we will add some additional columns to filter and make box plots. 

```
echo -e "sample\tchromosome\tstart_pos\tend_pos\tnumreads\tcovbases\tcoverage\tmeandepth\tmeanbaseq\tmeanmapq" > coverage_chrom.txt

for file in *_coverage.txt; do
    # Get a clean sample name (e.g., M10 or B1R1-14C-D10-E1)
    sample=$(basename "$file" _coverage.txt)
    
    # Grep pulls out the 14 chromosomes, and awk attaches the sample name to the full line ($0)
    grep -E "NC_134838.1|NC_134839.1|NC_134840.1|NC_134841.1|NC_134842.1|NC_134843.1|NC_134844.1|NC_134845.1|NC_134846.1|NC_134847.1|NC_134848.1|NC_134849.1|NC_134850.1|NC_134851.1" "$file" | \
    awk -v s="$sample" '{print s "\t" $0}' >> coverage_chrom.txt
done
```

This will essentially extract all of the information from the files. For now, I am developping code and looking at numbers in the 'chromosome_level_mapping.Rmd' file.

Unfortunately, it looks like some of my samples that have low mapping rates *also* have on average low depth. Definitely a meeting with Brent...on the whole, coverage looks pretty high. Sigh. So. We shall see. 


------

------
<div id='id-section36'/> 

### Entry 36: 2026-07-08

I messaged Brent to have a meeting, and this morning I am doing some reading about variable mapping rates. Here are some things that I have found and saved to my paper pile: 
* A triple wash in FSW has been used to remove algal contamination from daphnia studies of fresh and preserved samples and found to be highly effective (Benide et al. 2020)
* 

Questions for meeting with Brent: 
* what are implications of variable mapping rates on the rest of the data?
* If SNPs for downstream processes are highly filtered, is that stringent enough to overcome the issue?
* Are there other disciplines that face this issue? I imagine things like ancient DNA etc, so what are some interesting sources to consult/people in the department to talk to?
* At what point should a sample be straight up discarded?
* is there anything that can be done with the fact that there was more algae in particular trials? Is this a confounding factor in the experiment?

Samples of particular issue: day 20, 22C, family 1: very low pool size, and lowest coverage samples. 

Meeting with Brent notes:
* Use packages that can identify contamination: it is more powerful if you can quantify the contamination and precisely name it
* with quantification, the algae can be better accounted for
* new figure to make: coverage vs. mapping rate
  * how does low coverage affect allele frequency variation? (look at this on a graph)
* possibility: down sampling for coverage
* Joaquin can help out with variant calling questions
* People to talk to: Joaquin, Melissa, Elise, Nasreen, Danny, Emily Longman

------

------
<div id='id-section37'/> 

### Entry 37: 2026-07-09

I had a meeting with Nasreen regarding the samples with varying coverage. Working with ancient DNA, she had a very helpful perspective. Her advice was the following:

* use SNP filtering: set the filtering for the VCF production step to filter to the lowest coverage sample
* correction ML tree on filtered snps
* plink for filtering
* metagenomic screening tools: 
  * kracken (version 2 or unique (lower false positive rate) - Nasreen and her undergrad can help out)
  * metaphlan 4, molt (steeper learning curve)
  * blastm (steeper learning curve on backend; Danny and Emily Longman have also used this on the VACC)

------

------
<div id='id-section37'/> 

### Entry 38: 2026-07-10

Alright, I chatted with Joaquin and he reccomended the following things:
* filter sequences in fastp/fastqc down to 19 bp and filter out the Nextera transposase sequence. 
*Literally re-do the whole pipeline...lol. 


So, let's continue. Here is some edited code that he suggested for trimming.

#### 01_trim_array.sh version 1
```bash
#!/usr/bin/env bash
#
#SBATCH --job-name=stringent_trim
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4          
#SBATCH --mem=16G                   
#SBATCH --time=12:00:00
#SBATCH --partition=general
#SBATCH --array=1-70%20
#SBATCH --output=/gpfs2/scratch/edombro1/aus_mussels/data/trimmed_fq/fastqc_reports/trim_%A_%a.out
#SBATCH --error=/gpfs2/scratch/edombro1/aus_mussels/data/trimmed_fq/fastqc_reports/trim_%A_%a.err
#SBATCH --mail-type=ALL

# Load dependency + programs
module load gcc/13.3.0-xp3epyt
module load fastp/0.23.4-mjw7rak
module load fastqc

# Define directories that contain raw data (located in netfiles, not scratch)
DIR1="/netfiles/lockwood_lab/aus_mussels/data/raw/AGRF_NXGSQCAGRF25090171-1_23JW2NLT4"
DIR2="/netfiles/lockwood_lab/aus_mussels/data/raw/AGRF_NXGSQCAGRF25090171-2_23JW2NLT4"

# Workspace outputs
OUT_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/trimmed_fq"
mkdir -p ${OUT_DIR}/fastqc_reports

# Exact ground-truth sample path provided
SAMPLE_LIST="/users/e/d/edombro1/scratch/aus_mussels/data/trimmed/unique_samples.txt"
SAMPLE=$(sed -n "${SLURM_ARRAY_TASK_ID}p" $SAMPLE_LIST)

echo "Processing task ID ${SLURM_ARRAY_TASK_ID}: Sample ${SAMPLE}"

# Determine which folder this specific sample lives in
if ls ${DIR1}/${SAMPLE}_* >/dev/null 2>&1; then
    DATA_DIR=$DIR1
elif ls ${DIR2}/${SAMPLE}_* >/dev/null 2>&1; then
    DATA_DIR=$DIR2
else
    echo "ERROR: Sample ${SAMPLE} not found in either folder!"
    exit 1
fi

# Define temporary pipe file markers to skip writing intermediate 140GB merge files to disk
PIPE_R1="${OUT_DIR}/${SAMPLE}_r1.fifo"
PIPE_R2="${OUT_DIR}/${SAMPLE}_r2.fifo"
rm -f $PIPE_R1 $PIPE_R2
mkfifo $PIPE_R1 $PIPE_R2

echo "Streaming lane merging process on the fly for ${SAMPLE}..."
# Using zcat to decompress binary streams on the fly into the named pipe
zcat ${DATA_DIR}/${SAMPLE}_*L00*_R1.fastq.gz > $PIPE_R1 &
zcat ${DATA_DIR}/${SAMPLE}_*L00*_R2.fastq.gz > $PIPE_R2 &

echo "Running filtering on ${SAMPLE}..."
# This blends your adapter detection with your advisor's quality thresholds
# Explicitly removing Nextera transposase contamination
# Trimming front 19bp based on output analysis
fastp \
  --thread $SLURM_CPUS_PER_TASK \
  --in1 $PIPE_R1 \
  --in2 $PIPE_R2 \
  --out1 ${OUT_DIR}/${SAMPLE}_trimmed_R1.fastq.gz \
  --out2 ${OUT_DIR}/${SAMPLE}_trimmed_R2.fastq.gz \
  --html ${OUT_DIR}/${SAMPLE}_fastp.html \
  --json ${OUT_DIR}/${SAMPLE}_fastp.json \
  --detect_adapter_for_pe \
  --adapter_sequence CTGTCTCTTATACACATCT \
  --adapter_sequence_r2 CTGTCTCTTATACACATCT \
  --trim_front1 19 \
  --trim_front2 19 \
  --cut_tail 18 \
  --trim_poly_g \
  --trim_poly_x \
  --qualified_quality_phred 20 \
  --average_qual 18 \
  --length_required 30

# Clean up streaming pipes safely
rm -f $PIPE_R1 $PIPE_R2

echo "Generating FastQC metrics..."
fastqc -o ${OUT_DIR}/fastqc_reports -t $SLURM_CPUS_PER_TASK \
  ${OUT_DIR}/${SAMPLE}_trimmed_R1.fastq.gz \
  ${OUT_DIR}/${SAMPLE}_trimmed_R2.fastq.gz

echo "Finished processing ${SAMPLE} cleanly."
```

------

------
<div id='id-section39'/> 

### Entry 39: 2026-07-11

Alright, checked back and the process timed out, likely because of the weird intermediate merging step. I just got rid of that and I have made the following adjustments for speed. 

#### 01_trim_array.sh version 2
```bash
#!/usr/bin/env bash
#
#SBATCH --job-name=stringent_trim
#SBATCH --output=trim_%A_%a.out
#SBATCH --error=trim_%A_%a.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16          # Upped to 16 cores to process 70x data quickly
#SBATCH --mem=40G                   # Upped to 40G RAM to comfortably handle the heavy file processing
#SBATCH --time=12:00:00
#SBATCH --partition=general
#SBATCH --array=1-70%20
#SBATCH --mail-type=ALL

# Load dependency + programs
module load gcc/13.3.0-xp3epyt
module load fastp/0.23.4-mjw7rak
module load fastqc/0.12.1-qxseug5

# Define directories that contain raw data (located in netfiles, not scratch)
DIR1="/netfiles/lockwood_lab/aus_mussels/data/raw/AGRF_NXGSQCAGRF25090171-1_23JW2NLT4"
DIR2="/netfiles/lockwood_lab/aus_mussels/data/raw/AGRF_NXGSQCAGRF25090171-2_23JW2NLT4"

# Workspace outputs
OUT_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/trimmed_fq"
mkdir -p ${OUT_DIR}/fastqc_reports

# meta data files
SAMPLE_LIST="/users/e/d/edombro1/scratch/aus_mussels/data/trimmed/unique_samples.txt"
SAMPLE=$(sed -n "${SLURM_ARRAY_TASK_ID}p" $SAMPLE_LIST)

echo "Processing task ID ${SLURM_ARRAY_TASK_ID}: Sample ${SAMPLE}"

# Determine which folder this specific sample lives in
if ls ${DIR1}/${SAMPLE}_* >/dev/null 2>&1; then
    DATA_DIR=$DIR1
elif ls ${DIR2}/${SAMPLE}_* >/dev/null 2>&1; then
    DATA_DIR=$DIR2
else
    echo "ERROR: Sample ${SAMPLE} not found in either folder!"
    exit 1
fi

echo "Physically merging 8 lanes for ${SAMPLE} to disk..."
cat ${DATA_DIR}/${SAMPLE}_*L00*_R1.fastq.gz > ${OUT_DIR}/${SAMPLE}_merged_R1.fastq.gz
cat ${DATA_DIR}/${SAMPLE}_*L00*_R2.fastq.gz > ${OUT_DIR}/${SAMPLE}_merged_R2.fastq.gz

echo "Running filtering on merged file for ${SAMPLE}..."
# quality thresholds from Nunez lab
# Explicitly removing Nextera transposase contamination
# Trimming front 19bp based on output analysis
fastp \
  --thread $SLURM_CPUS_PER_TASK \
  --in1 ${OUT_DIR}/${SAMPLE}_merged_R1.fastq.gz \
  --in2 ${OUT_DIR}/${SAMPLE}_merged_R2.fastq.gz \
  --out1 ${OUT_DIR}/${SAMPLE}_trimmed_R1.fastq.gz \
  --out2 ${OUT_DIR}/${SAMPLE}_trimmed_R2.fastq.gz \
  --html ${OUT_DIR}/${SAMPLE}_fastp.html \
  --json ${OUT_DIR}/${SAMPLE}_fastp.json \
  --detect_adapter_for_pe \
  --adapter_sequence CTGTCTCTTATACACATCT \
  --adapter_sequence_r2 CTGTCTCTTATACACATCT \
  --trim_front1 19 \
  --trim_front2 19 \
  --cut_tail 18 \
  --trim_poly_g \
  --trim_poly_x \
  --qualified_quality_phred 20 \
  --average_qual 18 \
  --length_required 30

echo "Cleaning up temporary un-trimmed merged files to free up space..."
rm -f ${OUT_DIR}/${SAMPLE}_merged_R1.fastq.gz ${OUT_DIR}/${SAMPLE}_merged_R2.fastq.gz

echo "Generating FastQC metrics..."
fastqc -o ${OUT_DIR}/fastqc_reports -t $SLURM_CPUS_PER_TASK \
  ${OUT_DIR}/${SAMPLE}_trimmed_R1.fastq.gz \
  ${OUT_DIR}/${SAMPLE}_trimmed_R2.fastq.gz

echo "Finished processing ${SAMPLE} cleanly."
```

I ran `sbatch --array=1-1 01_trim_array.sh`
It worked, and now I will run `sbatch --array=2-70 01_trim_array.sh`

------

------
<div id='id-section40'/> 

### Entry 40: 2026-07-12

Alright; some notes about the script from last night. 
* The capacitor in the sbatch heading does nothing. Everything ran at the same time with the command `sbatch --array=2-70 01_trim_array.sh`. This isn't a big deal for now, but given the size of the other files, it likely would be a big deal. So just make sure to do the throttle in the command when I run it.
* The logs were put into the scripts folder. So those need to be moved to a 'logs' folder within the new directory. I should be able to do this using `mv trim_4* /users/e/d/edombro1/scratch/aus_mussels/data/trimmed_fq/logs`

running multiqc for a quick visualization before moving on: 
/gpfs2/scratch/edombro1/aus_mussels/data/trimmed_fq/multiqc/_%a.out

```
#!/bin/bash
#SBATCH --job-name=multiqc
#SBATCH --output=/gpfs2/scratch/edombro1/aus_mussels/data/trimmed_fq/multiqc/multiqc_%j.out
#SBATCH --error=/gpfs2/scratch/edombro1/aus_mussels/data/trimmed_fq/multiqc/multiqc_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=4G
#SBATCH --time=00:20:00
#SBATCH --partition=short

# script to visualize all fastq files at the same time

module load gcc/13.3.0-xp3epyt
module load py-multiqc/1.15-fmpaaj7

cd /gpfs2/scratch/aus_mussels/data/trimmed_fq
multiqc .
```

Okay, so trimming the first 20 base pairs did make things look a lot better. I think that was a good, worthwhile step. Next, I suppose I should check out the storage constraints and potentially clean some things up.

#### 02_map_cutadapt.sh
```bash
#!/usr/bin/env bash
#
#SBATCH --job-name=map_mussels
#SBATCH --output=/gpfs2/scratch/edombro1/aus_mussels/data/cram_alignments/logs/map_%A_%a.out
#SBATCH --error=/gpfs2/scratch/edombro1/aus_mussels/data/cram_alignments/logs/map_%A_%a.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --constraint=ib1
#SBATCH --cpus-per-task=16          # 16 cores gives bwa-mem2 massive speed
#SBATCH --mem=80G                   # 80G matches your committee member's recommendation for assembly loading
#SBATCH --time=48:00:00
#SBATCH --partition=general
#SBATCH --array=1-70
#SBATCH --mail-type=ALL

# Load cluster modules
module load bwa-mem2/2.2.1
module load gcc/13.3.0-xp3epyt
module load samtools/1.19.2-pfmpoam
module load qualimap

# Core computational variables
NTHREADS=$SLURM_CPUS_PER_TASK
SAMTOOLS_THREADS=$(($NTHREADS-1))
# MEM_NODE=$(($(($SLURM_MEM_PER_NODE/1024))-5)) cause issues

# Core computational variables
NTHREADS=$SLURM_CPUS_PER_TASK
SAMTOOLS_THREADS=$(($NTHREADS-1))
QUALIMAP_MEM=30  # Explicitly give Qualimap 30GB of RAM

# Ground-truth absolute paths
REFERENCE_DIR="/users/e/d/edombro1/scratch/aus_mussels/data/reference"
PATH_TO_ASSEMBLY="${REFERENCE_DIR}/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna"
PATH_TO_READS="/users/e/d/edombro1/scratch/aus_mussels/data/trimmed_fq"
SAMPLE_LIST="/users/e/d/edombro1/scratch/aus_mussels/data/trimmed/unique_samples.txt"

# Workspace output directories on gpfs2 scratch
OUT_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/cram_alignments"
mkdir -p ${OUT_DIR}/logs
mkdir -p ${OUT_DIR}/qualimap_reports

# Parse sample name from your unique list
SAMPLE=$(sed -n "${SLURM_ARRAY_TASK_ID}p" $SAMPLE_LIST)
echo "Starting mapping for Task ID ${SLURM_ARRAY_TASK_ID}: Sample ${SAMPLE}"

# Input read paths matches your fresh fastp output format
FReads="${PATH_TO_READS}/${SAMPLE}_trimmed_R1.fastq.gz"
RReads="${PATH_TO_READS}/${SAMPLE}_trimmed_R2.fastq.gz"

# Set up Read Group metadata tags for downstream variant calling
RGLB="LIB-${SAMPLE}"
RGSM="${SAMPLE}"

# STEP 1: Align, Sort, Mark Duplicates, and Filter directly to a CRAM footprint on-the-fly.
# We pass the -f 2 -F 3844 -q 20 criteria directly to avoid intermediate files.
echo "Running bwa-mem2 and streaming directly into filtered CRAM..."
bwa-mem2 mem \
  -M -t $NTHREADS \
  -R "@RG\tID:${SAMPLE}\tPL:ILLUMINA\tLB:${RGLB}\tSM:${RGSM}" \
  $PATH_TO_ASSEMBLY \
  $FReads \
  $RReads | \
samtools fixmate -u -m --threads $SAMTOOLS_THREADS - - | \
samtools sort -u -T ${SAMPLE}_tmp --threads $SAMTOOLS_THREADS - | \
samtools markdup -u --threads $SAMTOOLS_THREADS - - | \
samtools view -h -b -f 2 -F 3844 -q 20 --reference $PATH_TO_ASSEMBLY --threads $SAMTOOLS_THREADS -O CRAM -o ${OUT_DIR}/${SAMPLE}.filtered.dedup.cram -

# STEP 2: Coordinate index the final CRAM file (Required for downstream stats and tools)
echo "Indexing CRAM file..."
samtools index -@ $SAMTOOLS_THREADS ${OUT_DIR}/${SAMPLE}.filtered.dedup.cram

# STEP 3: Generate alignment metrics
echo "Calculating samtools stats..."
samtools stats --threads $SAMTOOLS_THREADS \
  --reference $PATH_TO_ASSEMBLY \
  ${OUT_DIR}/${SAMPLE}.filtered.dedup.cram > ${OUT_DIR}/${SAMPLE}.filtered.dedup.cramstats

# STEP 4: Run Qualimap validation
echo "Running Qualimap QC..."
qualimap bamqc \
  -bam ${OUT_DIR}/${SAMPLE}.filtered.dedup.cram \
  -outdir ${OUT_DIR}/qualimap_reports/${SAMPLE}_qualimap \
  --java-mem-size=${QUALIMAP_MEM}G

echo "Finished processing sample ${SAMPLE} successfully."
```

submitted a trial run. Let's see...

------

------
<div id='id-section41'/> 

### Entry 41: 2026-07-13

Everything looks like it worked pretty well. The cram file size that has been deduplicated and only contains unique reads is substantially smaller than the ones I've been working with: only about 5 Gb instead of 25. Additionally, the script ran relatively quickly, no where near approaching the 48 hour limit: it ran in about 4.5 hours (from 12:10 pm - 4:40 pm), and sorted, indexed, and deduplicated all in one script. Woo. I will take it. 

Here's some outputs that I got: 
```
# grep some samtools stats from the sample
grep ^SN B1R1-14C-D10-E1.filtered.dedup.cramstats
SN      raw total sequences:    227295128       # excluding supplementary and secondary reads
SN      filtered sequences:     0
SN      sequences:      227295128
SN      is sorted:      1
SN      1st fragments:  113650565
SN      last fragments: 113644563
SN      reads mapped:   227295128
SN      reads mapped and paired:        227295128       # paired-end technology bit set + both mates mapped
SN      reads unmapped: 0
SN      reads properly paired:  227295128       # proper-pair bit set
SN      reads paired:   227295128       # paired-end technology bit set
SN      reads duplicated:       0       # PCR or optical duplicate bit set
SN      reads MQ0:      0       # mapped and MQ=0
SN      reads QC failed:        0
SN      non-primary alignments: 0
SN      supplementary alignments:       0
SN      total length:   28527910035     # ignores clipping
SN      total first fragment length:    14265102981     # ignores clipping
SN      total last fragment length:     14262807054     # ignores clipping
SN      bases mapped:   28527910035     # ignores clipping
SN      bases mapped (cigar):   24037517578     # more accurate
SN      bases trimmed:  0
SN      bases duplicated:       0
SN      mismatches:     771279309       # from NM fields
SN      error rate:     3.208648e-02    # mismatches / bases mapped (cigar)
SN      average length: 126
SN      average first fragment length:  126
SN      average last fragment length:   126
SN      maximum length: 131
SN      maximum first fragment length:  131
SN      maximum last fragment length:   131
SN      average quality:        39.6
SN      insert size average:    212.8
SN      insert size standard deviation: 139.2
SN      inward oriented pairs:  90648905
SN      outward oriented pairs: 22998373
SN      pairs with other orientation:   0
SN      pairs on different chromosomes: 0
SN      percentage of properly paired reads (%):        100.0

# look at amount of total reads in file
module load gcc/13.3.0-xp3epyt
module load samtools/1.19.2-pfmpoam
samtools view -c B1R1-14C-D10-E1.filtered.dedup.cram
227295128

# look at stats output by samtools
samtools flagstat B1R1-14C-D10-E1.filtered.dedup.cram
227295128 + 0 in total (QC-passed reads + QC-failed reads)
227295128 + 0 primary
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
227295128 + 0 mapped (100.00% : N/A)
227295128 + 0 primary mapped (100.00% : N/A)
227295128 + 0 paired in sequencing
113650565 + 0 read1
113644563 + 0 read2
227295128 + 0 properly paired (100.00% : N/A)
227295128 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

Something to note is that the qualimap validation did not produce anything. This is likely a result of the .cram file usage, so here is some edited code that should directly use the reference to produce that. 

#### 02_cutadapt.sh qualimap edits
```
# STEP 4: Run Qualimap validation
echo "Running Qualimap QC..."
qualimap bamqc \
  -bam ${OUT_DIR}/${SAMPLE}.filtered.dedup.cram \
  -outdir ${OUT_DIR}/qualimap_reports/${SAMPLE}_qualimap \
  --java-mem-size=${QUALIMAP_MEM}G \
  -nw \
  --java-options="-Dsamjdk.reference_fasta=${PATH_TO_ASSEMBLY}"
```

When I ran this script, it looks like about 3 jobs are running at once even though I ran `sbatch --array=2-70%20 02_cutadapt.sh`. I think the 48 hours of wall time would really slow this down. 

From here, my next step is to run Bayepass for variant calling. I should look at Emily's scripts and go from there. 

Alright, let's take a look at Emily's script and go from there.
Source: https://github.com/emily-longman/Nucella_can_Pop_Genomics/blob/main/src/02_fastq_to_vcf/03_call_variants/03_variant_calling.sh


#### E. Longman's bayepass variant calling script
```
#!/usr/bin/env bash

# In the command line, run the following command: sbatch path/to/this/file.sh

# Request cluster resources ----------------------------------------------------

# Name this job
#SBATCH --job-name=variant_calling_freebayes

# Specify partition
#SBATCH --partition=general

# Request nodes
#SBATCH --nodes=1 

# Reserve walltime -- hh:mm:ss --30 hrs max
#SBATCH --time=30:00:00 

# Request memory for the entire job -- you can request --mem OR --mem-per-cpu
#SBATCH --mem=60G 

# Request CPU
#SBATCH --cpus-per-task=4

# Submit job array
#SBATCH --array=1-631%25

# Name output of this job using %x=job-name and %j=job-id
#SBATCH --output=./slurmOutput/%x.%A_%a.out # Standard output

# Receive emails when job begins and ends or fails
#SBATCH --mail-type=ALL
#SBATCH --mail-user=emily.longman@uvm.edu 

#--------------------------------------------------------------------------------

# This script will use freebayes to call variants.

# Note: Since the N. canaliculata genome consistent of many scaffolds, I chunked the genome into 50 scaffolds partitions to utilize an array structure.
# For each slurm array ID, freebayes is running over the 50 scaffolds using a loop then the vcf files are combined together.  

#--------------------------------------------------------------------------------

# Load modules 
module load gcc/13.3.0-xp3epyt
module load freebayes/1.3.6-r67va2b
module load bcftools/1.19-iq5mwek

#--------------------------------------------------------------------------------

# Define important file locations

# WORKING_FOLDER is the core folder where this pipeline is being run.
WORKING_FOLDER=/gpfs2/scratch/elongman/Nucella_can_Pop_Genomics

# This is the location where the reference genome is stored.
REFERENCE_FOLDER=/netfiles/pespenilab_share/Nucella/processed/Base_Genome/Base_Genome_Oct2024/Crassostrea_softmask

# This is the path to the reference genome.
REFERENCE=$REFERENCE_FOLDER/N.canaliculata_assembly.fasta.softmasked.fa

#--------------------------------------------------------------------------------

## Import master partition file 
GUIDE_FILE=$WORKING_FOLDER/guide_files/Scaffold_names_array.txt

#Example: -- the headers are just for descriptive purposes. The actual file has no headers. (dimensions: 2, 18919; 631 partitions)
# Scaffold name       # Partition
# Backbone_10001            1
# Backbone_10003            1
# Backbone_10004            1
# ....

#--------------------------------------------------------------------------------

# Determine partition to process 

# Echo slurm array task ID
echo ${SLURM_ARRAY_TASK_ID}

# Change directory 
cd $WORKING_FOLDER/data/processed/fastq_to_vcf

# Using the guide file, extract the scaffold names associated based on the Slurm array task ID for a given partition
awk '$2=='${SLURM_ARRAY_TASK_ID}'' $GUIDE_FILE | awk '{print $1}' > genome.scaffold.names.${SLURM_ARRAY_TASK_ID}.txt

#--------------------------------------------------------------------------------

# Generate Folders and files

# Move to working directory
cd $WORKING_FOLDER/data/processed/fastq_to_vcf

# This part of the script will check and generate, if necessary, all of the output folders used in the script

if [ -d "vcf_freebayes" ]
then echo "Working vcf_freebayes folder exist"; echo "Let's move on."; date
else echo "Working vcf_freebayes folder doesnt exist. Let's fix that."; mkdir $WORKING_FOLDER/data/processed/fastq_to_vcf/vcf_freebayes; date
fi

cd $WORKING_FOLDER/data/processed/fastq_to_vcf/vcf_freebayes

if [ -d "partitions" ]
then echo "Working partitions folder exist"; echo "Let's move on."; date
else echo "Working partitions folder doesnt exist. Let's fix that."; mkdir $WORKING_FOLDER/data/processed/fastq_to_vcf/vcf_freebayes/partitions; date
fi

cd $WORKING_FOLDER/data/processed/fastq_to_vcf/vcf_freebayes/partitions

if [ -d "genome.scaffold.names.${SLURM_ARRAY_TASK_ID}" ]
then echo "Working genome.scaffold.names.${SLURM_ARRAY_TASK_ID} folder exist"; echo "Let's move on."; date
else echo "Working genome.scaffold.names.${SLURM_ARRAY_TASK_ID} folder doesnt exist. Let's fix that."; mkdir $WORKING_FOLDER/data/processed/fastq_to_vcf/vcf_freebayes/partitions/genome.scaffold.names.${SLURM_ARRAY_TASK_ID}; date
fi

#--------------------------------------------------------------------------------

# Prepare bamlist
# This is a file with the name and full path of all the bam files to be processed.

# Move to bams folder
cd $WORKING_FOLDER/data/processed/fastq_to_vcf/RGSM_final_bams

# Create bamlist for all Nucella samples
ls *.bam > $WORKING_FOLDER/data/processed/fastq_to_vcf/guide_files/Nucella_pops_bam_names.list

BAMLIST=$WORKING_FOLDER/data/processed/fastq_to_vcf/guide_files/Nucella_pops_bam_names.list

#--------------------------------------------------------------------------------

# Use freebayes to call variants

# Note: 
# The freebayes algorithm exploits a neutral model of allele diffusion to impute most-confident genotypings across the
# entire population. In practice, the discriminant power of the method will improve if you run multiple samples simultaneously. 
# In other words, if your study has multiple individuals, you should run freebayes against them at the same time via a bamlist. 

# For the scaffolds in a given partition, generate a vcf file for each scaffold then cat them together. 

# Cat file of scaffold names and start while loop
cat $WORKING_FOLDER/data/processed/fastq_to_vcf/genome.scaffold.names.${SLURM_ARRAY_TASK_ID}.txt | \
while read SCAFFOLD 
do echo ${SCAFFOLD}

freebayes -f $REFERENCE -L $BAMLIST -r ${SCAFFOLD} -K -F 0.01 -C 1 -G 5 --limit-coverage 500 -n 4 -m 30 -q 20 | gzip -c > $WORKING_FOLDER/data/processed/fastq_to_vcf/vcf_freebayes/partitions/genome.scaffold.names.${SLURM_ARRAY_TASK_ID}/Nucella.freebayes.${SCAFFOLD}.vcf.gz

done 

# -K --pooled-continuous : Output all alleles which pass input filters, regardles of genotyping outcome or model.
## Least expensive option in time/memory because if we use pool-discrete it is necessary to specify a haploid pool size and it calculates the likelihoods for each possible configuration which can take a long time.

# -F --min-alternate-fraction N : Require at least this fraction of observations supporting an alternate allele within a single individual in order to evaluate the position.  default: 0.05
## In the case of Pool-seq it is better to reduce this value so as not to penalize rare alleles present in a pool.
## With the default value, any variant represented by <5% of reads in the pool would be ignored. 

# -C --min-alternate-count N : Require at least this count of observations supporting an alternate allele within a single individual in order to evaluate the position.  default: 2
## Reduce to 1 for the same reason as -F

# -G --min-alternate-total N : Require at least this count of observations supporting an alternate allele within the TOTAL population in order to use the allele in analysis.  default: 1
## Increased to 5. Given that we generally apply to many pools, avoid carrying around ultra rare alleles, which are probably sequencing errors. This also reduces computational costs.
## Caution however may have an impact for methods based on SFS.

# --limit-coverage N: Downsample per-sample coverage to this level if greater than this coverage. default: no limit

# -m --min-mapping-quality Q : Exclude alignments from analysis if they have a mapping quality less than Q.  default: 1
# -q --min-base-quality Q : Exclude alleles from analysis if their supporting base quality is less than Q.  default: 0
## Classic quality criteria (Note: may need to be readjusted if we recalibrate the Base Quality BQSR)?

# -n --use-best-n-alleles N : Evaluate only the best N SNP alleles, ranked by sum of supporting quality scores.  (Set to 0 to use all (i.e., default))
## Reduced to 4 (see recommendation for computational cost reduction). Be careful however because the other alleles are simply not considered (i.e., the real DP may vary from the actual DP, i.e., sum of coverage of the reported alleles)
## Most of the time, we will only retain bi-allelics (or very poorly covered alleles will be removed: see poolfstat)(in GATK HaplotypeCaller it is 7 by default because --max-alternate-alleles 6)

# --strict-vcf Generate strict VCF format (FORMAT/GQ will be an int)
# Genotype quality (not useful here since pooled-continuous) are given by default in log10 scale likelihood (=> heavy the output file)

#--------------------------------------------------------------------------------

# Combine the vcf files from all of the scaffolds in a given partition

bcftools concat \
$WORKING_FOLDER/data/processed/fastq_to_vcf/vcf_freebayes/partitions/genome.scaffold.names.${SLURM_ARRAY_TASK_ID}/*.vcf.gz \
-Oz -o $WORKING_FOLDER/data/processed/fastq_to_vcf/vcf_freebayes/partitions/genome.scaffold.names.${SLURM_ARRAY_TASK_ID}.vcf.gz

#--------------------------------------------------------------------------------

# Change directory
cd $WORKING_FOLDER/data/processed/fastq_to_vcf

# Housekeeping
rm genome.scaffold.names.${SLURM_ARRAY_TASK_ID}.txt
rm -R $WORKING_FOLDER/data/processed/fastq_to_vcf/vcf_freebayes/partitions/genome.scaffold.names.${SLURM_ARRAY_TASK_ID}

#--------------------------------------------------------------------------------

date
echo "done"

#--------------------------------------------------------------------------------

#### INFO and FORMAT field of the vcf

##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total read depth at the locus">
##INFO=<ID=DPB,Number=1,Type=Float,Description="Total read depth per bp at the locus; bases in reads overlapping / bases in haplotype">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Total number of alternate alleles in called genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1]">
##INFO=<ID=RO,Number=1,Type=Integer,Description="Count of full observations of the reference haplotype.">
##INFO=<ID=AO,Number=A,Type=Integer,Description="Count of full observations of this alternate haplotype.">
##INFO=<ID=PRO,Number=1,Type=Float,Description="Reference allele observation count, with partial observations recorded fractionally">
##INFO=<ID=PAO,Number=A,Type=Float,Description="Alternate allele observations, with partial observations recorded fractionally">
##INFO=<ID=QR,Number=1,Type=Integer,Description="Reference allele quality sum in phred">
##INFO=<ID=QA,Number=A,Type=Integer,Description="Alternate allele quality sum in phred">
##INFO=<ID=PQR,Number=1,Type=Float,Description="Reference allele quality sum in phred for partial observations">
##INFO=<ID=PQA,Number=A,Type=Float,Description="Alternate allele quality sum in phred for partial observations">
##INFO=<ID=SRF,Number=1,Type=Integer,Description="Number of reference observations on the forward strand">
##INFO=<ID=SRR,Number=1,Type=Integer,Description="Number of reference observations on the reverse strand">
##INFO=<ID=SAF,Number=A,Type=Integer,Description="Number of alternate observations on the forward strand">
##INFO=<ID=SAR,Number=A,Type=Integer,Description="Number of alternate observations on the reverse strand">
##INFO=<ID=SRP,Number=1,Type=Float,Description="Strand balance probability for the reference allele: Phred-scaled upper-bounds estimate of the probability of observing the deviation between SRF and SRR given E(SRF/SRR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=SAP,Number=A,Type=Float,Description="Strand balance probability for the alternate allele: Phred-scaled upper-bounds estimate of the probability of observing the deviation between SAF and SAR given E(SAF/SAR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=AB,Number=A,Type=Float,Description="Allele balance at heterozygous sites: a number between 0 and 1 representing the ratio of reads showing the reference allele to all reads, considering only reads from individuals called as heterozygous">
##INFO=<ID=ABP,Number=A,Type=Float,Description="Allele balance probability at heterozygous sites: Phred-scaled upper-bounds estimate of the probability of observing the deviation between ABR and ABA given E(ABR/ABA) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=RUN,Number=A,Type=Integer,Description="Run length: the number of consecutive repeats of the alternate allele in the reference genome">
##INFO=<ID=RPP,Number=A,Type=Float,Description="Read Placement Probability: Phred-scaled upper-bounds estimate of the probability of observing the deviation between RPL and RPR given E(RPL/RPR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=RPPR,Number=1,Type=Float,Description="Read Placement Probability for reference observations: Phred-scaled upper-bounds estimate of the probability of observing the deviation between RPL and RPR given E(RPL/RPR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=RPL,Number=A,Type=Float,Description="Reads Placed Left: number of reads supporting the alternate balanced to the left (5') of the alternate allele">
##INFO=<ID=RPR,Number=A,Type=Float,Description="Reads Placed Right: number of reads supporting the alternate balanced to the right (3') of the alternate allele">
##INFO=<ID=EPP,Number=A,Type=Float,Description="End Placement Probability: Phred-scaled upper-bounds estimate of the probability of observing the deviation between EL and ER given E(EL/ER) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=EPPR,Number=1,Type=Float,Description="End Placement Probability for reference observations: Phred-scaled upper-bounds estimate of the probability of observing the deviation between EL and ER given E(EL/ER) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=DPRA,Number=A,Type=Float,Description="Alternate allele depth ratio.  Ratio between depth in samples with each called alternate allele and those without.">
##INFO=<ID=ODDS,Number=1,Type=Float,Description="The log odds ratio of the best genotype combination to the second-best.">
##INFO=<ID=GTI,Number=1,Type=Integer,Description="Number of genotyping iterations required to reach convergence or bailout.">
##INFO=<ID=TYPE,Number=A,Type=String,Description="The type of allele, either snp, mnp, ins, del, or complex.">
##INFO=<ID=CIGAR,Number=A,Type=String,Description="The extended CIGAR representation of each alternate allele, with the exception that '=' is replaced by 'M' to ease VCF parsing.  Note that INDEL alleles do not have the first matched base (which is provided by default, per the spec) referred to by the CIGAR.">
##INFO=<ID=NUMALT,Number=1,Type=Integer,Description="Number of unique non-reference alleles in called genotypes at this position.">
##INFO=<ID=MEANALT,Number=A,Type=Float,Description="Mean number of unique non-reference allele observations per sample with the corresponding alternate alleles.">
##INFO=<ID=LEN,Number=A,Type=Integer,Description="allele length">
##INFO=<ID=MQM,Number=A,Type=Float,Description="Mean mapping quality of observed alternate alleles">
##INFO=<ID=MQMR,Number=1,Type=Float,Description="Mean mapping quality of observed reference alleles">
##INFO=<ID=PAIRED,Number=A,Type=Float,Description="Proportion of observed alternate alleles which are supported by properly paired read fragments">
##INFO=<ID=PAIREDR,Number=1,Type=Float,Description="Proportion of observed reference alleles which are supported by properly paired read fragments">
##INFO=<ID=MIN_DP,Number=1,Type=Integer,Description="Minimum depth in gVCF output block.">
##INFO=<ID=END,Number=1,Type=Integer,Description="Last position (inclusive) in gVCF output record.">
##INFO=<ID=technology.ILLUMINA,Number=A,Type=Float,Description="Fraction of observations supporting the alternate observed in reads from ILLUMINA">


##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Float,Description="Genotype Quality, the Phred-scaled marginal (or unconditional) probability of the called genotype">
##FORMAT=<ID=GL,Number=G,Type=Float,Description="Genotype Likelihood, log10-scaled likelihoods of the data given the called genotype for each possible genotype generated from the reference and alternate alleles given the sample ploidy">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Number of observation for each allele">
##FORMAT=<ID=RO,Number=1,Type=Integer,Description="Reference allele observation count">
##FORMAT=<ID=QR,Number=1,Type=Integer,Description="Sum of quality of the reference observations">
##FORMAT=<ID=AO,Number=A,Type=Integer,Description="Alternate allele observation count">
##FORMAT=<ID=QA,Number=A,Type=Integer,Description="Sum of quality of the alternate observations">
##FORMAT=<ID=MIN_DP,Number=1,Type=Integer,Description="Minimum depth in gVCF output block.">

```

So, Emily divided up this script into an array based on her 600+ scaffolds. It looks like my genome, having been already assembled and haplotype phased and not quite so mucus-y, is a bit cleaner. There are already 
* 14 chromosome scaffolds, and 
* 325 additional scaffolds
So, my array will utilize the existing samples and attempt to create some other files that are balanced to run the other stuff. 

Here is some code I will run to split things up: 

```
# This script reads your 339 targets, assigns the first 14 main chromosomes 
# to bins 1-14, and groups the remaining 325 scaffolds into bins of 15-20.
# (Adjust the 'per_bin' variable below to change how many small scaffolds share a slot)

awk 'NR==FNR {lengths[$1]=$2; next} 
{
    if (FNR <= 14) {
        print $1, FNR
    } else {
        # Groups remaining scaffolds (e.g., 50 per bin) starting at bin 15
        per_bin = 50 
        bin_num = 15 + int((FNR - 15) / per_bin)
        print $1, bin_num
    }
}' GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna.fai chrom_filter_bounds.txt > Scaffold_names_array.txt

# check the sizes of each bin to make sure they're not weirdly allocated
awk 'NR==FNR {lengths[$1]=$2; next} 
{
    if (FNR <= 14) {
        bin_num = FNR
    } else {
        bin_num = 15 + int((FNR - 15) / 50)
    }
    bin_lengths[bin_num] += lengths[$1]
} 
END {
    print "Bin_Number\tTotal_Length_BP"
    for (b in bin_lengths) {
        printf "Bin_%d\t\t%'\''d bp\n", b, bin_lengths[b]
    }
}' GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna.fai chrom_filter_bounds.txt | sort -V
```

This produced a two column file that has two columns: one with the scaffold name, one with a number 1-25. The first 14 chromosomes have their own assignment, but the smaller scaffolds have been grouped into clusters of 15 samples/scaffold. I also ran a check to see how big each bin is: 
Bin_1		0 bp
Bin_2		133,122,103 bp
Bin_3		115,872,679 bp
Bin_4		112,047,329 bp
Bin_5		104,860,103 bp
Bin_6		102,992,780 bp
Bin_7		102,858,672 bp
Bin_8		98,048,912 bp
Bin_9		97,139,405 bp
Bin_10		94,721,750 bp
Bin_11		91,363,364 bp
Bin_12		86,550,376 bp
Bin_13		81,349,889 bp
Bin_14		74,365,144 bp
Bin_15		79,629,639 bp
Bin_16		3,487,412 bp
Bin_17		2,396,303 bp
Bin_18		1,889,683 bp
Bin_19		1,507,108 bp
Bin_20		1,036,094 bp
Bin_21		132,831 bp
Bin_Number	Total_Length_BP
So, it looks like bin 1 was assigned to a header...let's fix that

```
awk 'NR==FNR {lengths[$1]=$2; next} 
# NR>1 skips the header line in chrom_filter_bounds.txt
FNR>1 {
    # Adjust FNR by subtracting 1 to account for the skipped header
    current_row = FNR - 1
    
    if (current_row <= 14) {
        bin_num = current_row
    } else {
        # Groups the remaining 325 small scaffolds into bins of 50
        bin_num = 15 + int((current_row - 15) / 50)
    }
    print $1, bin_num
}' GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna.fai chrom_filter_bounds.txt > Scaffold_names_array.txt
```

Next, I will have to update the file paths in the script and run a trial. Perhaps I can run the trial even as the cram files continue to populate? I'm not sure. 
I'm going to do my script editing in a new document. 

------

------
<div id='id-section42'/> 

### Entry 42: 2026-07-14

Notes from meeting with Melissa: 
* quantify algal contamination with specific species
* consider a standardized 25x coverage bottom for all SNPS
* when thinking about the snps for all samples, consider a snp matrix with snps and samples
  * the filtering requirements can be that ALL samples are required to have all SNPs
  * or, that most samples are required to have required snps
  * mess around with the missingness criteria and see how it impacts snps
* visualize multiple possiblilities as PCA or dendrogram to show relatedness
* see where biological realism falls apart
* attention to terminology: "family" in genetics refers to a single male / female cross
* major trade off: no data missingness (stringent filtering) vs. higher quality with sample dropping
* on PCA, the lowest coverage outliers could be an artifact of PCA mapping
* Look at Reids github for more information about subsequent steps with FreeBayes and poolfstat.

Summary to Brent: 
* Nasreen recommended filtering sample coverage down to what is present in the lowest individual and gave some good recommendations on metagenomics software for looking into the algae contamination
* Joaquin recommended more stringent filtering steps in the early stages as well as very strict SNP calling. He also threw out the idea of a SLiM simulation to test the question of how variable coverage across samples impacts later assessments of snps related to selection, which I think is interesting, but would take me a good while to implement. 
* Melissa's recommendation was to keep varying levels of "missingness" when SNP filtering, then compare sample clustering on the resulting PCAs. From there, we can make more informed decisions about whether or not individual samples need to be dropped or if stringent SNP filtering will produce clearer candidate SNPs. For example: run variant calling keeping SNPs that are present in 80% of the samples, and compare to a more stringent filtering situation. When visualized on a PCA or dendrogram, the different levels of filtering and individuals contributing to candidate SNPs can be assessed.
These steps give me a pretty clear game plan of where to go next. If you are around for the rest of the week, I am also happy to chat about this in person. For now, I am implementing some of Joaquin's filtering suggestions, then I will use FreeBayes to variant call and PoolFStat to start visualizing the data. 

------

------
<div id='id-section43'/> 

### Entry 43: 2026-07-15

Okay, so I ran the code Joaquin sent over with more stringent filtering steps. I am having regrets for filtering so stringently and throwing out the unmapped reads because Melissa also mentioned measuring and quantifying the algal contamination. Additionally, E. Longman mentioned that for 

------

------
<div id='id-section44'/> 

### Entry 44: 2026-07-16


#### extract samtools stats (cov_stat)

#### 03.1_samtools_summary.sh
```bash
#!/usr/bin/env bash
#SBATCH --job-name=chromo_coverage
#SBATCH --partition=short
#SBATCH --nodes=1
#SBATCH --time=00:20:00
#SBATCH --mem=8G
#SBATCH --cpus-per-task=4
#SBATCH --array=1-70%15
#SBATCH --output=/gpfs2/scratch/edombro1/aus_mussels/data/cram_alignments/logs/cov_%A_%a.out

# Load samtools
module load gcc/13.3.0-xp3epyt
module load samtools/1.19.2-pfmpoam

# Paths
REFERENCE_DIR="/users/e/d/edombro1/scratch/aus_mussels/data/reference"
PATH_TO_ASSEMBLY="${REFERENCE_DIR}/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna"
SAMPLE_LIST="/users/e/d/edombro1/scratch/aus_mussels/data/trimmed/unique_samples.txt"
OUT_DIR="/gpfs2/scratch/edombro1/aus_mussels/data/cram_alignments"

# Parse the sample name based on the SLURM Task ID
SAMPLE=$(sed -n "${SLURM_ARRAY_TASK_ID}p" $SAMPLE_LIST)

# Run fast, multi-threaded chromosome-by-chromosome coverage
samtools coverage \
  --threads 3 \
  --reference $PATH_TO_ASSEMBLY \
  ${OUT_DIR}/${SAMPLE}.filtered.dedup.cram \
  > ${OUT_DIR}/${SAMPLE}.chromosome_coverage.txt

```
Step 1: use an array to go through each sample and generate this chromosome coverage script. Then, we will move on to step 2, which will look at that script and loop through by grouping the primary scaffolds (chromosomes) and the samples. 

```bash

# Path to your list of 14 chromosomes
CHROM_LIST="/users/e/d/edombro1/scratch/aus_mussels/data/reference/primary_chromosomes.txt"

# Initialize the master CSV with explicit headers
echo "sample,chromosome,start,end,numreads,covbases,breadth_of_coverage,depth,meanmapq,percentage_gc" > master_qc_and_coverage.csv

# Loop over all your chromosome coverage files
for f in *.chromosome_coverage.txt; do
    SAMPLE=$(basename "$f" .chromosome_coverage.txt)
    echo "Filtering and compiling stats for ${SAMPLE}..."
    
    # Use awk to:
    # 1. Read main_chromosomes.txt into an associative array (FNR==NR)
    # 2. Match only those chromosomes in the sample file (FNR>1 && $1 in chroms)
    # 3. Print matching rows and calculate the weighted "all" totals for just these 14
    awk -F'\t' -v s="$SAMPLE" '
        NR==FNR { 
            chroms[$1]; 
            next 
        }
        FNR > 1 && ($1 in chroms) {
            # Print the individual chromosome line directly
            print s "," $1 "," $2 "," $3 "," $4 "," $5 "," $6 "," $7 "," $8 "," $9
            
            # Accumulate totals ONLY for these 14 chromosomes
            total_len += ($3 - $2);
            total_reads += $4;
            total_cov_bases += $5;
            sum_depth_x_len += ($7 * ($3 - $2));
            sum_mapq_x_len += ($8 * ($3 - $2));
            sum_gc_x_len += ($9 * ($3 - $2));
        }
        END {
            if (total_len > 0) {
                # Calculate True weighted statistics of ONLY the 14 chromosomes
                avg_breadth = (total_cov_bases / total_len) * 100;
                avg_depth = sum_depth_x_len / total_len;
                avg_mapq = sum_mapq_x_len / total_len;
                avg_gc = sum_gc_x_len / total_len;
                
                print s ",all,1," total_len "," total_reads "," total_cov_bases "," avg_breadth "," avg_depth "," avg_mapq "," avg_gc
            }
        }
    ' "$CHROM_LIST" "$f" >> master_qc_and_coverage.csv
done

echo "Finished! Clean dataset written to 'master_qc_and_coverage.csv'"
```

------

------
<div id='id-section45'/> 

### Entry 45: 2026-07-17

So, my Freebayes code timed out at 30 hours; which is why we run a check! I think the next move will be splitting the chromosomes into smaller windows, then running the script. For example, my array was 21 long; Longman's was 600+... so, let's use that method. Here's some code that I used to split the chromosome into smaller pieces. 

```bash
awk '
{
  chr=$1
  len=$2

  for(start=1; start<=len; start+=10000000){
    end=start+9999999
    if(end>len) end=len
    print chr ":" start "-" end
  }
}
' GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna.fai > regions_10Mb.txt
```

When I ran `wc -l regions_10Mb.txt`, I got 469 regions. So, my new array will be for 469 regions. I will update my freebayes script to reflect this, while still keeping the 30 hour time window. Hopefully it will go more quickly than that...

I changed the script and launched a test run. I will check back to see how it is doing. 

------

------
<div id='id-section46'/> 

### Entry 46: 2026-07-18


I came back to check on the script and it had not quite timed out at 30 hours...I am doing another trial of a different region with 48 hours to see how it goes. 

------

------
<div id='id-section47'/> 

### Entry 47: 2026-07-20

My test array of the 10 MB portion of the genome has been running for over 30 hours...godwilling, it will finish in the near future. My goals for today are to: 

* do research on meta genomics software (kraken, blast, etc.)
* decide a pipeline for looking at the algal contamination
* locate an algal genome for reference? 

Here's some notes on my research. 

* Papers that look at similar things: 
  * one about scallops (Gerdol et al. 2014);
  * one about HABs and bivalves (Griffith et al. 2019)
* Pipeline: 
  1. Run fastq on all samples
  2. Get pertinent algae genomes and download
    a. *Isochrysis sp., Pavlova sp., Tetraselmis sp., Thalassiosira weissflogii, and Thalassiosira pseudonana*
  3. Run kraken uniq on all samples (similar to multiqc)
  4. look at the breakdown of how things mapped...will also show prokaryotes and eukaryotes
  
When I did module spider for krakenuniq, this is what came up: 

To download the reference genomes for the algae, I will use these: 

#### download algal genomes from NCBI
```
#!/bin/bash
#SBATCH --job-name=download_ref
#SBATCH --partition=short
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --time=02:00:00
#SBATCH --output=download_%j.out
#SBATCH --error=download_%j.err
#SBATCH --mail-type=ALL

echo "Starting download of algal reference genomes..."; date

# ------------------------------------------------------------------
# 1. ISOCHRYSIS (Isochrysis galbana)
# ------------------------------------------------------------------
wget "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/018/136/815/GCA_018136815.1_ASM1813681v1/GCA_018136815.1_ASM1813681v1_genomic.fna.gz"

if [ -s "GCA_018136815.1_ASM1813681v1_genomic.fna.gz" ]
then 
    echo "Isochrysis reference genome successfully downloaded!"
else 
    echo "ERROR: Isochrysis reference genome did not download; check script."
fi

# ------------------------------------------------------------------
# 2. PAVLOVA (Diacronema lutheri - Common aquaculture strain)
# ------------------------------------------------------------------
wget "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/019/693/415/GCA_019693415.1_ASM1969341v1/GCA_019693415.1_ASM1969341v1_genomic.fna.gz"

if [ -s "GCA_019693415.1_ASM1969341v1_genomic.fna.gz" ]
then 
    echo "Pavlova (Diacronema) genome successfully downloaded."
else 
    echo "ERROR: Pavlova genome did not download; check script."
fi

# ------------------------------------------------------------------
# 3. TETRASELMIS (Tetraselmis chuii - Key bivalve hatchery feed)
# ------------------------------------------------------------------
wget "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/613/945/GCA_003613945.1_ASM361394v1/GCA_003613945.1_ASM361394v1_genomic.fna.gz"

if [ -s "GCA_003613945.1_ASM361394v1_genomic.fna.gz" ]
then 
    echo "Tetraselmis genome successfully downloaded."
else 
    echo "ERROR: Tetraselmis genome did not download; check script."
fi

# ------------------------------------------------------------------
# 4. THALASSIOSIRA (Thalassiosira pseudonana - Model diatom)
# ------------------------------------------------------------------
wget "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/149/405/GCF_000149405.2_ASM14940v2/GCF_000149405.2_ASM14940v2_genomic.fna.gz"

if [ -s "GCF_000149405.2_ASM14940v2_genomic.fna.gz" ]
then 
    echo "Thalassiosira genome successfully downloaded."
else 
    echo "ERROR: Thalassiosira genome did not download; check script."
fi

echo "All download tasks evaluated."; date"
```

I ran this and it took like 1 second (two hours was way over kill, also I did not need to submit it as a job probably). The only one that did not download was the tetra genome. 

  
Here is a script that I will look at to do this:

```
#!/bin/bash
#SBATCH --job-name=krakenuniq_array
#SBATCH --output=logs/krakenuniq_%A_%a.out
#SBATCH --error=logs/krakenuniq_%A_%a.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --mem=80G
#SBATCH --time=04:00:00
#SBATCH --array=1-70

# Load required module
module load krakenuniq/1.0.4

# 2. Define your paths (UPDATE THE DB_PATH)
DB_PATH="/path/to/vacc/krakenuniq/database" 
OUTPUT_DIR="./krakenuniq_outputs"
SAMPLE_LIST="sample_list.txt"

mkdir -p $OUTPUT_DIR logs

# 3. Pull the specific sample name for this Slurm task ID
SAMPLE_NAME=$(sed -n "${SLURM_ARRAY_TASK_ID}p" $SAMPLE_LIST)

echo "Starting KrakenUniq for sample: ${SAMPLE_NAME}"

# 4. Run KrakenUniq for paired-end data
krakenuniq --db $DB_PATH \
           --threads 12 \
           --paired \
           --gzip-compressed \
           --fastq-input \
           --report-file ${OUTPUT_DIR}/${SAMPLE_NAME}.report.txt \
           --output ${OUTPUT_DIR}/${SAMPLE_NAME}.output.txt \
           ${SAMPLE_NAME}_R1.fastq.gz ${SAMPLE_NAME}_R2.fastq.gz

echo "Finished processing ${SAMPLE_NAME}"
```

------


------
<div id='id-section48'/> 

### Entry 48: 2026-07-21

So, I was getting confused yesterday and making a script to index the algal reference genomes with bwa-mem2; however, I will be using fastq screen to look at algal contamination. This requires indexed samples using either bwa or bowtie2. I will check what is on the VACC and how to go from there. I wanted to use krakenuniq, however, there is only a database on the VACC that is for looking at microbes. It does not contain algal samples. On that note, I will check out kraken2 on the vacc potentially...

```
              Raw/Trimmed FASTQ Reads
                         │
        ┌────────────────┴────────────────┐
        ▼                                 ▼
  FastQ Screen                      KrakenUniq
 (Bowtie2 Indices)              (VACC Kraken DB)
 (in my case, bwa)                        |
        │                                 │
  Target: Diet Algae                Target: Bacteria,
  & Host Genome                     Archaea, Viruses
        │                                 │
        └────────────────┬────────────────┘
                         ▼
                   MultiQC Report
        (Combined view of Host %, Diet %, 
           and Microbial Contamination)

```

I will use bwa because I am familiar with that syntax more than bowtie.


#### 01.1_contamination_index.sh
```
#!/bin/bash
#SBATCH --job-name=index_algae
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time=10:00:00
#SBATCH --output=/users/e/d/edombro1/scratch/aus_mussels/data/reference/algae_genomes/logs/index_%j.out
#SBATCH --error=/users/e/d/edombro1/scratch/aus_mussels/data/reference/algae_genomes/logs/index_%j.err
#SBATCH --mail-type=ALL

# ------------------------------------------------------------------
# Setup & Directories
# ------------------------------------------------------------------
mussel_dir="/users/e/d/edombro1/scratch/aus_mussels/data/reference"
algae_dir="/users/e/d/edombro1/scratch/aus_mussels/data/reference/algae_genomes"
log_dir="${algae_dir}/logs"

# Ensure the logs directory exists before processing
mkdir -p "${log_dir}"

# Enable strict error handling
set -e

# ------------------------------------------------------------------
# Symlink Mussel Genome into Algae Directory
# ------------------------------------------------------------------
mussel_fasta_name="GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna"
original_mussel_path="${mussel_dir}/${mussel_fasta_name}"
target_mussel_path="${algae_dir}/${mussel_fasta_name}"

echo "Creating symlink for Mussel reference in ${algae_dir}..."
ln -sf "${original_mussel_path}" "${target_mussel_path}"

# Load bwa and dependency
module load gcc/13.3.0-xp3epyt
module load bwa/0.7.17-iqv3cxl

echo "=== Starting BWA Indexing Pipeline: $(date) ==="

# create specific function (run_bwa_index) to 1. unzip ref if neeeded; and 2. run command bwa index
# Helper function for explicit indexing checks
run_bwa_index() {
    local ref_file="$1"
    local species_label="$2"

    echo "----------------------------------------------------"
    echo "Processing ${species_label}..."

    # Decompress if gzipped
    if [[ "${ref_file}" == *.gz ]]; then
        echo "Decompressing ${ref_file}..."
        gunzip -k -f "${ref_file}"
        ref_file="${ref_file%.gz}"
    fi

    # Verify uncompressed FASTA exists
    if [[ ! -f "${ref_file}" ]]; then
        echo "[ERROR] Reference file ${ref_file} not found!" >&2
        exit 1
    fi

    # Execute indexing
    echo "Running 'bwa index' on ${ref_file}..."
    if bwa index "${ref_file}"; then
        echo "[SUCCESS] Indexing complete for ${species_label}."
    else
        echo "[ERROR] BWA indexing failed for ${species_label}!" >&2
        exit 1
    fi
}

# ------------------------------------------------------------------
# 1. MUSSEL REFERENCE
# ------------------------------------------------------------------
run_bwa_index "${mussel_dir}/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna" "Mytilus galloprovincialis"

# ------------------------------------------------------------------
# 2. ALGAL REFERENCES
# ------------------------------------------------------------------
# ISOCHRYSIS (Isochrysis galbana)
run_bwa_index "${algae_dir}/GCA_018136815.1_ASM1813681v1_genomic.fna.gz" "Isochrysis galbana"

# PAVLOVA (Diacronema lutheri)
run_bwa_index "${algae_dir}/GCA_019693415.1_ASM1969341v1_genomic.fna.gz" "Diacronema lutheri"

# TETRASELMIS (Tetraselmis chuii)
run_bwa_index "${algae_dir}/GCA_026401115.1_UNIGE_Tchui_1.0_genomic.fna.gz" "Tetraselmis chuii"

# THALASSIOSIRA (Thalassiosira pseudonana)
run_bwa_index "${algae_dir}/GCF_000149405.2_ASM14940v2_genomic.fna.gz" "Thalassiosira pseudonana"

echo "----------------------------------------------------"
echo "=== All BWA indexing tasks completed successfully: $(date) ==="
```

okay; stupidly, I let the mussel files overwrite my original indexed mussel genome. So, when the script finishes with the mussel samples, I need to go back and do the following.
1. move the new indexed files to the algae contamination folder
2. re-run my original reference indexing pipeline (thankfully, that is literally just opening a tmux with srun and doing this: 'bwa-mem2 index GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna')

...so all is not lost. It will be fixed soon! 

Next, I generated files with 1Mb regions of my genome (1700 of them). I then updated my freebayes script to skip highly repetitive regions. I am running two test files. We shall see. Here's the code for generating the guide files: 

```
module load module load gcc/13.3.0-xp3epyt
module load bedtools2/2.31.1-xip5kr5

# Define index and output file paths
REF_INDEX="/users/e/d/edombro1/scratch/aus_mussels/data/reference/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna.fai"
OUTPUT_1MB_FILE="/users/e/d/edombro1/scratch/aus_mussels/data/reference/regions_1Mb.txt"

# Make 1Mb windows (1-based format)
bedtools makewindows -g "$REF_INDEX" -w 1000000 | awk '{print $1":"$2+1"-"$3}' > "$OUTPUT_1MB_FILE"

# Count lines (this is your upper bound for the array)
wc -l "$OUTPUT_1MB_FILE"
```

------

------
<div id='id-section49'/> 

### Entry 48: 2026-07-22

I launched the first 500 lines of my freebayes array. It is running...I tried to launch all 1700 files at once, but there is a limit on the VACC for 1000 files at a time. 

Next, I messed around a bit with my algae contamination scripts. I have the following documents, but could not get them to launch. 

```
# ------------------------------------------------------------------
# FastQ Screen Configuration for Diagnostic Algal QC
# ------------------------------------------------------------------

# Specify BWA as the aligner
BOWTIE2 bwa

# ------------------------------------------------------------------
# Databases / References (Use full path without extension)
# ------------------------------------------------------------------

# Host Mussel Reference
DATABASE Mussel /users/e/d/edombro1/scratch/aus_mussels/data/reference/algae_genomes/GCF_965363235.1_xbMytGall1.hap1.1_genomic.fna

# 1. Isochrysis galbana
DATABASE Isochrysis /users/e/d/edombro1/scratch/aus_mussels/data/reference/algae_genomes/GCA_018136815.1_ASM1813681v1_genomic.fna

# 2. Diacronema lutheri
DATABASE Diacronema /users/e/d/edombro1/scratch/aus_mussels/data/reference/algae_genomes/GCA_019693415.1_ASM1969341v1_genomic.fna

# 3. Tetraselmis chuii
DATABASE Tetraselmis /users/e/d/edombro1/scratch/aus_mussels/data/reference/algae_genomes/GCA_026401115.1_UNIGE_Tchui_1.0_genomic.fna

# 4. Thalassiosira pseudonana
DATABASE Thalassiosira /users/e/d/edombro1/scratch/aus_mussels/data/reference/algae_genomes/GCF_000149405.2_ASM14940v2_genomic.fna
```

```
#!/bin/bash
#SBATCH --job-name=fastq_screen_algae
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --time=12:00:00
#SBATCH --output=/users/e/d/edombro1/scratch/aus_mussels/data/reference/algae_genomes/logs/screen_%j.out
#SBATCH --error=/users/e/d/edombro1/scratch/aus_mussels/data/reference/algae_genomes/logs/screen_%j.err
#SBATCH --mail-type=ALL

# Enable strict error handling
set -e

# ------------------------------------------------------------------
# Directories
# ------------------------------------------------------------------
algae_dir="/users/e/d/edombro1/scratch/aus_mussels/data/reference/algae_genomes"
conf_file="${algae_dir}/fastq_screen.conf"
out_dir="${algae_dir}/fastq_screen_results"
log_dir="${algae_dir}/logs"

# Adjust this path to where your larval WGS FASTQ files live:
fastq_dir="/users/e/d/edombro1/scratch/aus_mussels/data/trimmed_fq"

mkdir -p "${out_dir}"
mkdir -p "${log_dir}"

# ------------------------------------------------------------------
# Modules and fastq screen download
# ------------------------------------------------------------------
module load gcc/13.3.0-xp3epyt
module load bwa/0.7.17-iqv3cxl
# module load fastq-screen 
fastq_screen_bin="${algae_dir}/FastQ-Screen-0.15.3/fastq_screen"

echo "=== Starting FastQ Screen Run: $(date) ==="

# ------------------------------------------------------------------
# Run FastQ Screen
# ------------------------------------------------------------------
# Option A: Sample a representative subset (100k reads) for fast diagnostic QC
"${fastq_screen_bin}" \
    --conf "${conf_file}" \
    --outdir "${out_dir}" \
    --threads 8 \
    --aligner bwa \
    --subset 100000 \
    "${fastq_dir}"/*.fastq.gz

echo "=== FastQ Screen Completed: $(date) ==="
```

I had to download fastq-screen; it was not already on the VACC. Can't get this running though, will check back in tomorrow. 
------

------
<div id='id-section50'/> 

### Entry 48: 2026-07-23

My array is still running; yay! I have the successful message from many of them that they finished...here is the command I used to check: `grep -w "completed successfully." variant_calling_freebayes.4687431_*` 
I ran that in the logs folder; I need to do a version where the log *doesn't* have that to check what has not successfully ran.

Additionally, I updated the fastq screen script. It was running into an issue yesterday because I loaded the module, then directly loaded the command. Since I downloaded this from the internet to a new file I needed to directly mention it using a variable...also, my fastq file path was wrong. It is up and running now! Yay! That is good news. Will check back in when things continue. Some other goals while these things run: 

* variant filtering script
* different files for screening snps
* vcf concatination script

just some thoughts for now...

------